### ISSUE TITLE
DateTimeField(default=datetime.datetime.now)

### ISSUE THREAD

**Issue by bright-pan** [Scille/umongo#100]
hi,

why the defaut value is invalid in DateTimeField?

DateTimeField(default=datetime.datetime.now)

**Comment by bright-pan** [comment]
i fix it , use DateTimeField(missing=datetime.datetime.now()).

**Comment by lafrech** [comment]
Don't do that.

Do

DateTimeField(missing=datetime.datetime.now).

instead.

See? You need to pass a callable. Otherwise, `now` is executed at import time and you always get the same date.
