### ISSUE TITLE
Wrapping Validation Errors

### ISSUE THREAD

**Issue by cngo-github** [Scille/umongo#113]
How can I wrap the validation errors thrown by registered Documents? For example, I want to catch the validation errors thrown by umongo and throw my own custom exceptions.

**Comment by touilleMan** [comment]
umongo raises a `umongo.exceptions.ValidationError` (in fact a [`marshmallow.exceptions.ValidatitonError`](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/exceptions.py#L11)) exception so you can catch this pretty easily:

```python
class MyDoc(Document):
    ...

doc = MyDoc()
try:
    doc.commit()
except ValidationError as exc:
    exc.messages  # dict or list containing the errors
```

Another possibility would be to use the i18n (internationalization) support to modify the error messages, you can have [a look at this example](https://github.com/Scille/umongo/tree/master/examples/flask).

**Comment by cngo-github** [comment]
@touilleMan Thanks for the reply. I should have been more clear about what I was looking for. When I was using mongoengine, I would override the `validation()` method for all my documents so that whenever someone tries to make a document with invalid data, the exception thrown is a custom one, instead of the exception thrown by mongoengine. The calling code would not have to catch the error and throw the custom one. This was done for various reasons, but primarily, it was so that the rest of the codebase was not tied to whatever ODM/framework that the database package used. Therefore, when we decide to change the ODM, in this case from mongoengine to umongo, we don't have to change much of the code outside of the package that works directly with the database. In short, what I'm looking for is the equivalent of the `validate()` method for umongo Documents.

**Comment by touilleMan** [comment]
What you want to do is to customize the implementation of the document (by opposition of the template you define when creating a class without doing `instance.register(MyDoc)`)
Here is the code that should do the trick (yeah, it's a bit complexe):

```python
from pymongo import MongoClient
import umongo
from umongo.frameworks.pymongo import PyMongoBuilder, PyMongoDocument
from umongo.instance import LazyLoaderInstance


# Our custom exception
class SmurfError(Exception):
    pass


# Custom behavior document implementation
class SmurfDocumentImplementation(PyMongoDocument):
    # umongo will check if this `opts` field is defined inside the class or by a
    # parent to determine if the constructed class is user defined new Document
    # (i.e. a Document binded to a collection in mongodb) or a generic
    # implementation like we are defining now.
    opts = PyMongoDocument.opts

    # Here we do our customization
    def __setattr__(self, *args):
        try:
            super().__setattr__(*args)
        except umongo.ValidationError as exc:
            raise SmurfError(exc.messages)

    def __setitem__(self, *args):
        try:
            super().__setitem__(*args)
        except umongo.ValidationError as exc:
            raise SmurfError(exc.messages)


# Now we must define a builder which aims at turning a document template
# into it equivalent document implementation
class SmurfBuilder(PyMongoBuilder):
    BASE_DOCUMENT_CLS = SmurfDocumentImplementation


# We declare an instance class working with this type of builder
class SmurfInstance(LazyLoaderInstance):
    def __init__(self, *args, **kwargs):
        self.BUILDER_CLS = SmurfBuilder
        super().__init__(*args, **kwargs)

# optional step: `register_builder` allows us to use `umongo.Instance(db)`
# instead of directly using `SmurfInstance(db)`
umongo.frameworks.register_builder(SmurfBuilder)

# Now we can do regular umongo stuff ;-)
db = MongoClient().test
instance = umongo.Instance(db)


@instance.register
class Doc(umongo.Document):
    x = umongo.fields.StringField()


my_doc = Doc()
my_doc['x'] = 42  # raises `SmurfError: ['Not a valid string.']`
```

However, there is a much simpler solution:
```python
db = MongoClient().test
instance = umongo.Instance(db)

# We define a mixin class which is only responsible for overloading what we need
class OverwriteErrorMixin:
    def __setattr__(self, *args):
        try:
            super().__setattr__(*args)
        except umongo.ValidationError as exc:
            raise SmurfError(exc.messages)

    def __setitem__(self, *args):
        try:
            super().__setitem__(*args)
        except umongo.ValidationError as exc:
            raise SmurfError(exc.messages)


# The trick is to provid the mixin before the base Document class, this way MRO resolution order
# will first call our custom setattr/setitem code which will wrap the real function, allowing us to
# catch and modify the excetion !
@instance.register
class Doc(OverwriteErrorMixin, umongo.Document):
    x = umongo.fields.StringField()


my_doc = Doc()
my_doc['x'] = 42  # raises `SmurfError: ['Not a valid string.']`
```

**Comment by cngo-github** [comment]
Thanks @touilleMan.
