### ISSUE TITLE
Document.ensure_indexes() doesn't work for mongomock

### ISSUE THREAD

**Issue by cngo-github** [Scille/umongo#114]
So I've been testing out `umongo` and have run into the following problem:

The method `ensure_indexes()` doesn't work for the `mongomock` client when following the tutorial. It does work for `motor` and `pymongo`, however. I am using `umongo==0.14`, `pymongo==3.4.0`, `motor==1.1`, and `mongomock==3.7.0`.

This works:

```
import pymongo
conn = pymongo.MongoClient()
instance = umongo.Instance(conn.test)
@instance.register
class WithUniqueEmail(umongo.Document):
    email = umongo.fields.StrField(unique=True)
WithUniqueEmail.ensure_indexes()
```

As does this:

```
import motor
conn = motor.motor_asyncio.AsyncIOMotorClient()
instance = umongo.Instance(conn.test)
@instance.register
class WithUniqueEmail(umongo.Document):
    email = umongo.fields.StrField(unique=True)
WithUniqueEmail.ensure_indexes()
```
However, this fails:

```
import mongomock
conn = mongomock.MongoClient()
instance = umongo.Instance(conn.test)
@instance.register
class WithUniqueEmail(umongo.Document):
    email = umongo.fields.StrField(unique=True)
WithUniqueEmail.ensure_indexes()
```

with the following exception:

```
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/cngo/.local/lib/python3.6/site-packages/umongo/frameworks/pymongo.py", line 208, in ensure_indexes
        cls.collection.create_indexes(cls.opts.indexes)
TypeError: 'Collection' object is not callable
```

Currently, I am just not calling `ensure_indexes()` when using `mongomock`, but it would be nice to have this fixed so I can just swap `MongoClient`s without worrying about that.

**Comment by touilleMan** [comment]
Well mongomock lacks some fonctionalities of the real pymongo.
I've [submitted a PR](https://github.com/mongomock/mongomock/pull/325) fixing a lot of issues I had to make mongomock compatible with run a bit test suite (~1100 tests) from one of my applications.

Until it is merge (btw you can add a message to the PR thread to help motivating the maintainer ^^), you can install the patched version through my github fork with pip doing:
```
$ pip install git+https://github.com/touilleMan/mongomock.git@c5a77e28bca2cbe724b092845802cff75de4d4fe
```

**Comment by cngo-github** [comment]
@touilleMan Thanks. I have posted on that PR as requested.
