### ISSUE TITLE
Working with Non-strict MongoDB collection definition

### ISSUE THREAD

**Issue by ipfans** [Scille/umongo#115]
Sometimes I need to define a Document with part of document field for read only.

```json
{"_id":"xxx", "keyA": "hello", "keyB":2}
```
In some cases I only need keyA value:

```python
@db.register
class Data(Document):
    keyA = fields.StringField()

Data.find_one({keyA: "hello"})
```

But when I use umongo in this case, I got error:

```
  ....
  File ".../site-packages/umongo/data_proxy.py", line 67, in from_mongo
    field = self._fields_from_mongo_key[k]
KeyError: 'keyB'
```

So how can I got Data instance from non-strict definition?

**Comment by touilleMan** [comment]
Hi,
f0a7a5d should solve you trouble ^^
Basically I've added a new meta option `strict` that can disable the key check on document coming from mongo (but strill keep field checking for data coming from user):

```python
@self.instance.register
class StrictDoc(Document):
    a = fields.IntField()

@self.instance.register
class NonStrictDoc(Document):
    a = fields.IntField()

    class Meta:
        strict = False

data_with_bonus = {'a': 42, 'b': 'foo'}
with pytest.raises(KeyError):
    StrictDoc.build_from_mongo(data_with_bonus)

non_strict_doc = NonStrictDoc.build_from_mongo(data_with_bonus)
assert non_strict_doc.to_mongo() == data_with_bonus
non_strict_doc.dump() == {'a': 42}

with pytest.raises(exceptions.ValidationError) as exc:
    NonStrictDoc(a=42, b='foo')
assert exc.value.messages == {'_schema': ['Unknown field name b.']}
```

**Comment by touilleMan** [comment]
btw: just released v0.15.0 with this fix

**Comment by ipfans** [comment]
Wonderful, thanks for your works.

But I also notice that documents still not updated ;)

**Comment by touilleMan** [comment]
> But I also notice that documents still not updated ;)

You mean documentation ?

**Comment by ipfans** [comment]
yes, I made a mistake

**Comment by touilleMan** [comment]
I've added the `strict` field here http://umongo.readthedocs.io/en/latest/apireference.html#umongo.document.DocumentOpts
