### ISSUE TITLE
flake8 settings?

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#119]
Hi.

Trying to copy your tox / flake8 settings for another project, I'm wondering:

`tox.ini`:

    flake8 examples tests umongo

`setup.cfg`:

    [flake8]
    exclude = .git,docs,restkit/compat.py,env,venv,.ropeproject,_sandbox,tests,examples

Looks like in `tox` we ask `flake8` to check tests and examples, but then we exclude those directories in `flake8` config.

Am I missing something?

**Comment by touilleMan** [comment]
As you suspect, this is an error in the configuration ;-)

**Comment by lafrech** [comment]
OK, I wasn't 100% sure. I just sent a PR to fix this.
