### ISSUE TITLE
pymongo2 and data_objects.List

### ISSUE THREAD

**Issue by imbolc** [Scille/umongo#12]
When I run next code:
```
user = User.find_one({"email": 'vegeta@over9000.com'})
print(user.friends)
```

With **pymongo driver + pymongo3**, i have:
```
umongo.data_objects.List([<object umongo.dal.pymongo.PyMongoReference(document=User, pk=ObjectId('572192eb444bcb21df700488'))>])>
```

But if I run the same code with **pymongo driver + pymongo2.8**, I have:
```
<object umongo.data_objects.List([])>
```

So `data_objects.List` doesn't work with motor.

**Comment by touilleMan** [comment]
I couldn't reproduce the trouble with the enclosed script

```bash
$ . ./venv_pymongo/bin/activate
$ python test.py
<object umongo.data_objects.List([<object umongo.dal.pymongo.PyMongoReference(document=User, pk=ObjectId('5717562813adf27bb26ec820'))>])>
$ . ./venv_motor/bin/activate
$ python test.py
<object umongo.data_objects.List([<object umongo.dal.motor_asyncio.MotorAsyncIOReference(document=User, pk=ObjectId('5717562813adf27bb26ec820'))>])>
```

Are you sure your database has not been dropped before your test with motor ?

[test.py.txt](https://github.com/Scille/umongo/files/240351/test.py.txt)

**Comment by imbolc** [comment]
Oh, I'm sorry, I just tested `pymongo.MongoClient` with pymongo-2.8. But as you already mention, it doesn't intent to work. Now I tested `AsyncIOMotorClient()`, it works in both (await and yield from) styles.
Only `MotorAsyncIOReference` [does not work with await](https://github.com/Scille/umongo/issues/11).
