### ISSUE TITLE
Create ODM from configuration files

### ISSUE THREAD

**Issue by PatrickChen83** [Scille/umongo#125]
A configuration file (like Schema in Mongoose) can be shared among different clients (which is often why we need ODM). Right now, to implement this we have to get involve into python meta classes, and I think it would be great if it is implemented in the umongo module.

**Comment by touilleMan** [comment]
What are you thinking about ?
Different ODM support different options (same option sometime with different names...) so this schema would be only umongo compatible. But then you could also keep your umongo schema in a special package (with only umongo as dependency there) that is shared among your applications.

**Comment by PatrickChen83** [comment]
Sorry if I didn't elaborate clearly. The scenario is that, we have mongo clients implemented in different languages. To adapt to the frequently changed schema, one has to keep his schema in a file (often in JSON format) and create the model (by differnt languages) at runtime.

Therefore, the problem would become how can we generate umongo model based on the configuration file. It's ok that different ODMs support different options, because we can always transform the configuration file to fulfill different ODMs' requirements.

Right now, to create a umongo schema like this one

```python
@instance.register
class User(Document):
    email = fields.EmailField(required=True, unique=True)
    birthday = fields.DateTimeField(validate=validate.Range(min=datetime(1900, 1, 1)))
    friends = fields.ListField(fields.ReferenceField("User"))

    class Meta:
        collection = db.user
```

would be 

```python
NewClass = type("User", (object,), {
    "email": fields.EmailField(required=True, unique=True),
    # and more...
})

NewClass = instance.register(NewClass)
```
(I haven't run this snippet, but I think it will work)

So a good feature would be create this class from a python dict. What do you think?

**Comment by touilleMan** [comment]
I understand your usecase now.
I think your way of doing it (dynamically creating umongo classes after parsing your json) is the right one.

You should create a standalone project from this, this way you can standardize your json format and generate document for multiple odm (like mongoengine) on top of umongo by just adding a small translation module.
