### ISSUE TITLE
Dereferencing using Motor

### ISSUE THREAD

**Issue by cipriantarta** [Scille/umongo#127]
Hi there,
I'm using umongo with the Motor driver.

I have the following documents:

```python
from umongo import fields


class Community(Document):
    name = fields.StringField()
    brands = fields.ListField(fields.ReferenceField('Brand'))

class Brand(Document):
    name = fields.StringField()
```

So using marshmellow with `fields = ('id', 'name', 'brands')`, whenever i do a GET /communities, I get the brand id as a nested document in my response, which is fine as a default behaviour, but I'd like to be able to have the brands dereferenced.

How would I go about doing that, considering I can't use `.fetch()` in the `get_attribute()` method of the serializer since it's a generator because of motor.

So instead of this:

```JavaScript
{
    "id": "5a0c31d9d0fba69956a4cab0",
    "name": "some community",
    "brands": [
        "5a0d5f2dd0fba6b738bc2da8"
    ]
}
```

I want:

```JavaScript
{
    "id": "5a0c31d9d0fba69956a4cab0",
    "name": "some community",
    "brands": [
        {
            "5a0d5f2dd0fba6b738bc2da8",
            "name": "some brand"
        }
    ]
}
```

Thanks!

**Comment by touilleMan** [comment]
Hi,

I think you should cook your data before serializing them.
- First you get from database the community document
- Then you iterate over it brands and do a `fetch` for each one. You can also gather all the ids and call the database once in a batch for much better performances.
- Finally you can do the serialization. The trick here you the `Reference` object has a `._document` field that contains the document once you called `fetch` so you can use this. Another solution would be to serialize the batched results I was talking before.

Remember you can customize the marshmallow schema you created from the umongo document, so you can make it ignore a field, or provide a context to the marshmallow schema and pick in it the serialized form you want for a field.

**Comment by cipriantarta** [comment]
Thanks, it's what I did, thought there would be an easier way to do this, like a get_reference() method on the document that one could override which by default would return just the object ID.
