### ISSUE TITLE
Updating a dynamic document with validation

### ISSUE THREAD

**Issue by Relrin** [Scille/umongo#132]
Hi,

I'm trying to deal with updating a dynamic document with passing a validation process before applying changes. The project have tests that's make ensure that everything is going as expected, but they're returning errors instead:

```
_______________________________________ test_worker_returns_updated_player_statistics_with_extra_fields ________________________________________Traceback (most recent call last):
  File "/app/tests/test_update_player_statistics.py", line 106, in test_worker_returns_updated_player_statistics_with_extra_fields
    assert Response.CONTENT_FIELD_NAME in response.keys()
AssertionError: assert 'content' in dict_keys(['error', 'event-name'])
 +  where 'content' = Response.CONTENT_FIELD_NAME
 +  and   dict_keys(['error', 'event-name']) = <built-in method keys of dict object at 0x7f86ee7bdd38>()
 +    where <built-in method keys of dict object at 0x7f86ee7bdd38> = {'error': {'details': {'_schema': ['Unknown field name winrate.', 'Unknown field name nickname.']}, 'type': 'ValidationError'}, 'event-name': 'event-name'}.keys
```

This errors is raised by a couple of issues:
1) The processing worker is using the default Marshmallow schema for serializing and send the response after it. 
2) In the case of updating document the worker is using a custom schema for it, and it was passed successfully, trying to apply those changes to the document. After validating, the worker is trying to save a result, but instead of it, passing one more time the validating process with the default schema.

Based on this description, I have a couple of questions:
1) Does it possible to disable the default generated Marshmallow schema, so that I could control the validation process separately and save the changes directly without passing validation one more time?
2) In the actual moment of time Marshmallow isn't providing any methods for saving extra fields (which weren't specified) in your data, and, therefore, a developer must override a load/loads methods for doing it manually. I've tried to set up the `strict=False` option in the code, so that I could the validate the specified fields and won't touching to unspecified fields. Any suggestions/ideas how it can be done?

Links to source code:
- [The used document](https://github.com/OpenMatchmaking/microservice-player-statistics/blob/feature-crud-tests/player-statistics/app/statistics/documents.py#L11-L52) with MongoDb
- [The custom schema](https://github.com/OpenMatchmaking/microservice-player-statistics/blob/feature-crud-tests/player-statistics/app/statistics/schemas.py#L27-L60) for validating an input
- [AMQP Worker](https://github.com/OpenMatchmaking/microservice-player-statistics/blob/feature-crud-tests/player-statistics/app/workers/update_player_statistics.py#L26-L49) that's using a custom schema during processing request

**Comment by touilleMan** [comment]
> Does it possible to disable the default generated Marshmallow schema, so that I could control the validation process separately and save the changes directly without passing validation one more time?

The data validation is done by the DataProxy class, you can bypass it this way:
```python
my_doc = MyDoc()
my_doc._data  # here is the DataProxy

# The two are equivalent
my_doc.foo = 42
my_doc._data.set('foo', 42) 

# Now we totally bypass the validation
my_doc._data._data['foo'] = 42
```

However I would advice against doing this given you weaken a lot the guarantees umongo gives you on your database's consistency.
Normally you should have a first marshmallow schema to sanitize user inputs, then use the returned data to do you business logic (which can be pretty close to nothing if you only do CRUD) and eventually update the umongo document. This way it's not a trouble if the api exposed to the user is not 100% compatible with your database schema.

> In the actual moment of time Marshmallow isn't providing any methods for saving extra fields (which weren't specified) 

Have you tried the DictField for this (https://github.com/Scille/umongo/blob/master/umongo/fields.py#L54) ?

**Comment by Relrin** [comment]
> Have you tried the DictField for this (https://github.com/Scille/umongo/blob/master/umongo/fields.py#L54) ?

I saw this type of field, however I'd like to make the document as dynamic instead of nesting data in the additional field (in this case is DictField). 

As you can see [here](https://github.com/OpenMatchmaking/microservice-player-statistics/blob/feature-crud-tests/player-statistics/app/statistics/documents.py), I enable the "strict=True" to make the document as dynamic. But unfortunately, it won't let me to specify extra fields when they were provided.

**Comment by touilleMan** [comment]
`strict=False` tells umongo not to raise exception if the data from the database contains more fields than what's declared in the schema.

I think you'd better use schema inheritance for this usecase.

**Comment by Relrin** [comment]
Okay, I understood. Thank you for the answer.
