### ISSUE TITLE
Ability to add unique compound index

### ISSUE THREAD

**Issue by akolechkin** [Scille/umongo#137]
It's useful to be able to define two or more fields as single index. 
Sample from the official documentation: https://docs.mongodb.com/manual/core/index-unique/#unique-compound-index.

the use-case:

```
class Book(Document):

    author = StrField()
    title = StrField()
    pages = IntField()

    class Meta:
        indexes = ('pages',)
        unique_indexes = (('author', 'title'),)
```

Internally we can modify the original parse_index function https://github.com/Scille/umongo/blob/master/umongo/indexes.py#L20 and pass unique argument into that function, and then parse those two attributes from Meta in builder just like we do for unique/non unique indexes from fields in _collect_indexes https://github.com/Scille/umongo/blob/master/umongo/builder.py#L59

**Comment by xlionx** [comment]
@akolechkin Try to use:
```python    
class Meta:
    indexes = ({'key': ['author', 'title'], 'unique': True},)
```

**Comment by touilleMan** [comment]
thanks @xlionx for providing the answer ;-)
