### ISSUE TITLE
do not update on commit()

### ISSUE THREAD

**Issue by ribx** [Scille/umongo#138]
I am just implementing lazy migrations (#94). I removed a field and replaced it with a list. so the name changed from "field_id" to "fields". Loading with the "from_mongo()" overload works fine:

```
    def from_mongo(self, data, partial=None):

        if data["_schema_version"] == 1:
            if 'field_id' in data:
                data['fields'] = [FieldEmbeddedDoc(field_id=data['field_id'], percentage=1.0)]
                del data['media_id']

        return super(ProcedureSteps, self).from_mongo(data, partial)
```

But when this object is then returned from the client after editing, the `document.commit()` call will generate only an update statement and this is hard coded in line 104:

https://github.com/Scille/umongo/blob/4b4322bcd5037fdf416bb8fbabb8e51af4bdd984/umongo/frameworks/pymongo.py#L78-L110

a simple `document.commit(update=False)` would allow me to overwrite/delete the old values, and have my migration in one place only (`from_mongo()`).

My work around for now is not updating the "_schema_version" in the from_mongo() function, but after editing in `pre_update()`:

```
    def pre_update(self):

        if self._data.get("_schema_version") == 1:
            self._data.update({
                "field_id": missing,
                "_schema_version": 2,
            })
```

**Comment by ribx** [comment]
turns out, my workaround does not work, as only fields are saved/changed in the database, so I need this option to don't update but replace my object. So workaround for this will be having the old field still in the schema around, which is not what you typically want.

Maybe I am also doing this totally wrong here, I am happy for any advice.

**Comment by ribx** [comment]
workaroundaround:
```
    field_id = fields.ObjectIdField()

    def pre_update(self):

        if self._data.get("_schema_version") == 1:
            self._data._data["field_id"] = missing
            self._data._mark_as_modified("field_id")
            self._data.update({
                "_schema_version": 2,
            })
```

**Comment by lafrech** [comment]
I don't think `commit(update=True)` would work, for the same reason.

My advice to do this with umongo would be to keep the old field in the schema.

Closing this for now. Feel free to comment.
