### ISSUE TITLE
Document.created 

### ISSUE THREAD

**Issue by imbolc** [Scille/umongo#14]
Maybe it will be better to rename this to something like `is_created`? Because it's common practice to use `created` and `updated` for time of creating and updating of document.

**Comment by touilleMan** [comment]
Seems a nice idea to keep user experience smoother, i'll put it in the next release :+1:

**Comment by touilleMan** [comment]
done in 8193cdcb6a434e41b8241123ce3f173cfb5de48e (be careful, v0.8.0 brought a lot of changes)
