### ISSUE TITLE
Registered documents via lazy clients are working as synchronous instead of async

### ISSUE THREAD

**Issue by Relrin** [Scille/umongo#143]
Hello,

I'm trying to figure out why the registered table works as the blocking / synchronous document in MongoDB, instead of async (via the latest version of Motor driver). In the code below, I'd specified a lazy client in Sanic application config and after it trying to register a simple "Artist" document for demonstration purposes. 

So, idea for the typical "hello world" is pretty straightforward:
1) Create a new instance of Artist
2) Save it via the `commit()` call 
3) Return a response to the client

However, the code is blocking inside of the handler, when I'm typing `await artist.commit()` and without the `await` keyword it works as expected. Could you help me with this issue, and help me to figure out why the Lazy client isn't working as expected? (as async implementation)

P.S. The `sanic-mongodb-extension` is just a small package that I made for using with Sanic framework. And it doing nothing special, except that [initializes the environment](https://github.com/Relrin/sanic-mongodb-extension/blob/master/sanic_mongodb_ext/__init__.py) for usage.

```python
from sanic import Sanic, response
from sanic_mongodb_ext import MongoDbExtension
from umongo import Document, MotorAsyncIOInstance
from umongo.fields import StringField

app = Sanic(__name__)
app.config.update({
    "MONGODB_DATABASE": "app",
    "MONGODB_URI": "mongodb://user:password@127.0.0.1:27017",
    "LAZY_UMONGO": MotorAsyncIOInstance(),
})
MongoDbExtension(app) 
instance = app.config["LAZY_UMONGO"] 


@instance.register
class Artist(Document):
    name = StringField(required=True, allow_none=False)


from inspect import iscoroutine

@app.route("/")
async def handle(request):
    artist = Artist(name="A new rockstar!")
    print(iscoroutine(artist.commit))  # False (but must be True)
    await artist.commit()   # <-- blocking is happening here
    return response.json(artist.dump())

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)
```

Requirements of the example: 
```
marshmallow==2.15.4
motor==2.0.0
sanic==0.8.3
sanic-base-extension==0.1.1
sanic-mongodb-extension==0.2.0
umongo==0.15.0
```

**Comment by xlionx** [comment]
@Relrin If you want to use lazy instance you have to call  ```instance.init(db)```

Example from documentation:
```python
>>> from umongo import TxMongoInstance 
>>> instance = TxMongoInstance()
>>> @instance.register
... class Dog(Document):
... pass
>>> # Don't try to use Dog (except for inheritance) now ! 
>>> db = create_txmongo_database()
>>> instance.init(db)
>>> # Now instance is ready
>>> yield Dog().commit()
```

**Comment by Relrin** [comment]
Thank you for the answer!
