### ISSUE TITLE
EmbeddedField self Reference

### ISSUE THREAD

**Issue by cyrilis** [Scille/umongo#144]
Hi there,

I like this library, and I used it in my recent projects. Then I run into an issue:

I need to self reference a EmbeddedField in Schema Declaration: 

```Python
@instance.register
class Param(EmbeddedDocument):
	name = fields.StringField(required=True)
	type = fields.StringField()
    default = fields.DictField(allow_none=True)
    required = fields.BooleanField(missing=False)
    value = fields.DictField(allow_none=True)

	# Below is the self reference trying.
	children = fields.ListField(fields.EmbeddedField("Param"))
```

Run it and it raised an Error:
```
Unknown embedded document class `Param`
```

How can I make a EmbeddedField self Reference? 

[I found a example usage in a test file, but it was commented](https://github.com/Scille/umongo/blob/master/tests/test_query_mapper.py#L21)

Can you help me out? 

Thanks a lot!

**Comment by lafrech** [comment]
This was fixed in #322 but not tested.

Adding a test in #144.
