### ISSUE TITLE
Bulk insert/update

### ISSUE THREAD

**Issue by tapkain** [Scille/umongo#146]
From the examples, I see that commit accepts only self instance, does it mean that for 200 records I will make 200 queries? If umongo supports bulk insert, please share an example, because I could not find it, Thanks in advance.

**Comment by lafrech** [comment]
Indeed, there is no direct support for bulk insert/update. An object instance can only commit/save itself.

You can still do bulk insert/update by accessing the collection object, but then you're bypassing umongo and the object layer.
