### ISSUE TITLE
Drop Python 3.4?

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#152]
Same reason [it was dropped in marshmallow 3](https://github.com/marshmallow-code/marshmallow/pull/804) (it is old). Plus, we won't be able to support both marshmallow 3 and Python 3.4.

Apart from removing the 3.4 tests (or testing on 3.5 instead), would that make any difference?

Asynchronous stuff was improved in Python 3.5. Would that be an opportunity to improve the async drivers? (I don't use them, so I don't really mind, but if it's more or less a find'n replace, I can help.)

**Comment by touilleMan** [comment]
Yep, dropping 3.4 is a big plus for asynchronous stuff (replacing all `yield from` by `await` is a big plus !)
So I totally agree on this ;-)

**Comment by lafrech** [comment]
Done. v2.0 will be Python 3.4 free.

I don't use async and I'm not familiar with it, so I won't do the `yield from` -> `await` migration. Is it just a find'n replace?

**Comment by touilleMan** [comment]
You would also have to replace the asyncio.coroutine by async keyword, and
that should be it ;-)

Le ven. 8 mars 2019 22:21, Jérôme Lafréchoux <notifications@github.com> a
écrit :

**Comment by lafrech** [comment]
I tried a naive find'n replace approach and there seems to be a bit more than that. I had to add `async` before a few function definitions, and there are still a few tests failing.

I'd rather not do that myself. Anyone interested can submit a PR.

Do you think this would be a breaking change?

I mean if I release a 2.0 now, can this be done in 2.x or will it have to wait until 3.0?

**Comment by touilleMan** [comment]
see #179
