### ISSUE TITLE
Docs not updated on RTD

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#166]
Looks like the docs are not updated on RTD.

https://umongo.readthedocs.io/

Both latest and stable point to d033918 (1.0.0) in spite of 1.1.0 and more recent commits..

**Comment by touilleMan** [comment]
should be ok now (had to fix this https://docs.readthedocs.io/en/latest/webhooks.html#i-was-warned-i-shouldn-t-use-github-services)

**Comment by lafrech** [comment]
Thanks.

I released `v1.2.0` 20 minutes ago.

Latest still points to 1.0.0.
Stable still points to 1.1.0.

**Comment by touilleMan** [comment]
Maybe the build was slow: right now it seems latest point to 1.2.0 and stable to 1.1.0...
![image](https://user-images.githubusercontent.com/3187637/52518119-ece05080-2c45-11e9-9597-d7e7de4bfe9a.png)
