### ISSUE TITLE
Tests fail if python-dateutil is installed

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#17]
I'm having issues running the tests.

The docs say:

```
$ flake8 umongo
$ py.test tests
$ tox
```

#### Running py.test from Debian Jessie

I'm using a virtualenv, but `py.test` does not call `py.test` version from the virtualenv and actually, I don't know how to let it find it. I installed Debian Jessie's packaged pytest version `python3-pytest` (v 2.6.3, while latest from pip is 2.9.2). To make sure it uses python virtualenv version, I call it like this:

    python $(which py.test-3.4) tests

Using this command, I get a lot of errors related to `skipif` (see PR https://github.com/Scille/umongo/pull/16).

I also have a `datetime` issue:

```
====================================================== test session starts ======================================================
platform linux -- Python 3.4.2 -- py-1.4.25 -- pytest-2.6.3
collected 133 items 

tests/test_data_proxy.py ..............
tests/test_document.py ...................
tests/test_fields.py .F..x......
tests/test_i18n.py ...
tests/test_indexes.py .....
tests/test_inheritance.py ....
tests/test_instance.py .........
tests/test_query_mapper.py ..
tests/frameworks/test_mongomock.py s
tests/frameworks/test_motor_asyncio.py ssssssssssssssssssssss
tests/frameworks/test_pymongo.py sssssssssssssssssssss
tests/frameworks/test_txmongo.py ssssssssssssssssssssss

=========================================================== FAILURES ============================================================
___________________________________________________ TestFields.test_datetime ____________________________________________________

self = <tests.test_fields.TestFields object at 0x7f58d52d9be0>

    def test_datetime(self):
    
        class MySchema(EmbeddedSchema):
            a = fields.DateTimeField()
    
        s = MySchema(strict=True)
        data, _ = s.load({'a': datetime(2016, 8, 6)})
        assert data['a'] == datetime(2016, 8, 6)
        data, _ = s.load({'a': "2016-08-06T00:00:00Z"})
>       assert data['a'] == datetime(2016, 8, 6)
E       assert datetime.datetime(2016, 8, 6, 0, 0, tzinfo=tzutc()) == datetime.datetime(2016, 8, 6, 0, 0)
E        +  where datetime.datetime(2016, 8, 6, 0, 0) = datetime(2016, 8, 6)

tests/test_fields.py:98: AssertionError
================================== 1 failed, 65 passed, 66 skipped, 1 xfailed in 0.67 seconds ===================================
```

Is Jessie's py.test supposed to be "supported" or should we only use latest version from pip (in which case I'd appreciate a hint as I don't know how to run it without tox)?

#### Running tox and latest py.test

Both errors don't appear when running

    tox -e py34-pymongo

which I suppose uses pytest from virtualenv. So these issues may be due to py.test itself.

Using tox, I get a lot of flake8 errors (including errors in umongo's dependencies) and the report says a test xfailed, but the test that failed with Jessie's pytest passes.

```
tests/test_data_proxy.py ..............
tests/test_document.py ...................
tests/test_fields.py ....x......
tests/test_i18n.py ...
tests/test_indexes.py .....
tests/test_inheritance.py ....
tests/test_instance.py .........
tests/test_query_mapper.py ..
tests/frameworks/test_mongomock.py s
tests/frameworks/test_motor_asyncio.py ssssssssssssssssssssss
tests/frameworks/test_pymongo.py sssssssssssssssssssss
tests/frameworks/test_txmongo.py ssssssssssssssssssssss
```

**Comment by touilleMan** [comment]
> I'm using a virtualenv, but py.test does not call py.test version from the virtualenv and actually, I don't know how to let it find it

You should have a look at [tox.ini](https://github.com/Scille/umongo/blob/master/tox.ini), it describe what to install & run in a virtual env for the testing. You can also have a look at the [logs from travis](https://travis-ci.org/Scille/umongo/jobs/136958042)

I personally never use the distrubution's package for installing python tools:

```shell
$ cd ./umongo
$ virtualenv -p /usr/bin/python3 venv
$ . ./venv/bin/activate
$ pip install -e .  # installing umongo and it deps
$ # pytest is not yet installed in the virtualenv, if we run `py.test`, the system will try to run the one installed via apt-get (even if it's a python2 version !)
$ pip install pytest
$ py.test # now we are using virtualenv's pytest
```

> I installed Debian Jessie's packaged pytest version python3-pytest (v 2.6.3, while latest from pip is 2.9.2). To make sure it uses python virtualenv version

I have the same trouble with pytest 2.6.3, it seems we requires `pytest>=2.8`. I've documented it here d9d884953dc421eec001d317bea2f78c57311aa9 and there  705693921cb576fcd6aa75490ed3ebe935c02cab

> Using tox, I get a lot of flake8 errors (including errors in umongo's dependencies) and the report says a test xfailed, but the test that failed with Jessie's pytest passes.

Given the command run for flake8 is `flake8 .` it will try to check every directory within the root umongo. Thus if you have a `venv` dir there it will be checked as well...
ebc1674fa60da1e290b3294bc407e6d66325b54f correct this by asking flake8 to only check `tests`, `examples` and `umongo` dirs

**Comment by lafrech** [comment]
Thanks for the doc update and the flake "fix".

I created a new virtualenv with -no-site-packages and `pip`ed py.test and now I have a working setup.

(For the record, py.test 2.8 is backported on Jessie.)

**Comment by lafrech** [comment]
The datetime related test failure described above actually still occurs as soon as I install `python-dateutil` in my virtualenv.

This package is [recommended by marshmallow](https://github.com/marshmallow-code/marshmallow) and [mandatory for some operations](https://github.com/marshmallow-code/marshmallow/blob/c49afd611fcabcb7fb46f1fefb6f22a96b2dfa8e/marshmallow/utils.py#L234).

I'll rename this issue "Tests fail if `python-dateutil` is installed".

**Comment by touilleMan** [comment]
You're right about this: dateutil provides much better datetime deserialization especially regarding timezones.

So I've added python-dateutil as mandatory dependency to have a consistent behavior (see 43f6439029861bd7b402541d54f57d23159e310f).
