### ISSUE TITLE
Use mixins in schema declarations

### ISSUE THREAD

**Issue by gerasim13** [Scille/umongo#188]
Hello. Is there any way to use mixins with umongo Document class?
I have following structures:

```
class A(EmbeddedDocument):
  field1 = StringField()
  field2 = StringField()
  ...
  field99 = StringField()


class B(Document):
  field1 = StringField()
  field2 = StringField()
  ...
  field99 = StringField()
  items = ListField(EmbeddedDocumentField(A))
```

I want to put all of my fields to another class and use it as mixin for A and B. Is it possible in umongo?

**Comment by lafrech** [comment]
I think it should work but I never tried.

Did you try?

**Comment by gerasim13** [comment]
Yes i tried this and fields does not appears in marshmallow schemas

**Comment by gerasim13** [comment]
I wrote this decorator which adds desired behavior.

```
def add_mixins(*mixins):
    def decorator(cls):
        for mixin in mixins:
            for name, field in mixin.__dict__.items():
                if not field or not isinstance(field, Field):
                    continue
                setattr(cls, name, field)
        return cls
    return decorator

class ProductMixin:
    alias = StringField(required=True, allow_none=False)
    title = StringField(required=True, allow_none=False)

@instance.register
@add_mixins(ProductMixin)
class Product(Document):
  pass
```

**Comment by lafrech** [comment]
Right. I just fell into this myself.

I think this could be fixed by modifying `_collect_schema_attrs` in builder.py. Make it recursive, and change parameter to `template` instead of `template.__dict__`.

I don't have time for this right now but I'd be happy to merge a PR implementing it.

**Comment by lafrech** [comment]
@gerasim13 #267 should fix this.

There'an an issue with your implementation: the mixin overrides the doc class fields in case of name collision, while expected behaviour would be the doc class overriding the mixin. This is why I use `setdefault` in #267.
