### ISSUE TITLE
how to set write_concer

### ISSUE THREAD

**Issue by lomoonmoonbird** [Scille/umongo#192]
how to set wrtie_concer on db or update,insert syntax?

**Comment by lafrech** [comment]
Not sure what you mean. IIUC, you want to set write concern on a collection.

There is no specific support for this in umongo.

You can do that directly from your DB driver. For instance, for pymongo, see https://pymongo.readthedocs.io/en/stable/api/pymongo/database.html#pymongo.database.Database.create_collection.

We could try to wrap this feature in umongo but it wouldn't have much added value so I don't think it is worth the added API surface.
