### ISSUE TITLE
how to update with push operator

### ISSUE THREAD

**Issue by lomoonmoonbird** [Scille/umongo#194]
if a record has a list field , and wanna to push one object to this list, how to do that?

**Comment by vasu-vise** [comment]
You could use the append()method. For example
```
user = User.find_one({"id": ObjectId("<some object id>")})
car = Car.find_one({"id": ObjectId("<some object id>")})
car.buyer.append(user)
await car.commit()
```

Note:
Since this buyer is a list, you can append the same object multiple time at different indexes

**Comment by vasupal1996** [comment]
You could use the append()method. For example
```
user = User.find_one({"id": ObjectId("<some object id>")})
car = Car.find_one({"id": ObjectId("<some object id>")})
car.buyer.append(user)
await car.commit()
```

Note:
Since this buyer is a list, you can append the same object multiple time at different indexes

**Comment by lomoonmoonbird** [comment]
so all the operation, for example, push to a list , add to a set, or update one object into a specified position, should complete after find it .

**Comment by lomoonmoonbird** [comment]
question document:
{
"_id": "xxxx",
"name": "kim",
"age": 14,
"questions": [
    {"question_id": "a", "body": "first question", "answer": "first answer"},
    {"question_id": "b", "body": "second question", "answer": "second answer"}
]
}
if want to update question_id = a in questions:
original mongodb :
db.question.update({"_id": "xxxx", "questions.question_id": "a"}, {"$set": {"questions.$.answer": "first another answer"}})

how to do that with umongo

**Comment by lafrech** [comment]
We can't really help you until you show some code (the definition of your `Document`s).

Basically, you define your objects using umongo schemas (`Document`s) and fields (`Field`s), like shown in the docs.

Then, to update a document, you retrieve it, modify it, then commit it, like @vasupal1996 shown above.

Once you have written some code, if you still have specific questions, you may post here or on SO to get some help.
