### ISSUE TITLE
ListField(EmbeddedField): need to manually declare modifications in EmbeddedField

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#20]
When an embedded document is modified in a `ListField`, the modification is not automatically detected. The list by itself is not modified, but its elements are mutables, so there either they should notify `ListField` when they are modified, either `ListField` should check its elements when asked for changes.

Here's a (failing) test: https://github.com/Nobatek/umongo/tree/embeddeddoc_listfield

Is this known issue? I'm not sure how to fix it. I tried overriding `is_modified` and `clear_modified` in `List`, but I ended up breaking things.

Current workaround is calling `set_modified` on the `ListField` explicitly when modifying an element (see comment in test).

**Comment by touilleMan** [comment]
I've made a fix for this: eb86cacc299fd19a0e6f2fcd876139cfc0ac7ee4
