### ISSUE TITLE
Is there any way to allow unknown fields in the creation of a new document?

### ISSUE THREAD

**Issue by git-albertomarin** [Scille/umongo#204]
I would like to do something like the following

```python
class Dog(Document):
    class Meta:
        strict = False

dog = Dog(name="Lassie", breed="Golden Retriever")
```

But when I try that I still receive the following:
`'Unknown field name name.', 'Unknown field name breed.'`

I thought `strict = False` was supposed to allow unknown fields but it turns out that only applies to fields retrieved from the mongo collection. Is there any way to achieve what I am trying to do?

**Comment by lafrech** [comment]
I'm afraid there is no easy way to do that.

You'd need to modify `DataProxy` to maintain a list of the unknown field names. And it wouldn't work if the [de|se]rialization is not trivial, unless perhaps you use some a mapping to guess the field type based on the data type.
