### ISSUE TITLE
Prevent dumping _id field

### ISSUE THREAD

**Issue by Gonzalo933** [Scille/umongo#217]
Currently, the only way I found to prevent dumping the "_id" field of a document (when doing `User.dump()` is the following one:

```
from umongo import Document

class User(Document):
    email = fields.EmailField(required=True, unique=True)

    @post_dump()
    def remove_id_field(self, user_instance):
        del user_instance["id"]
        return user_instance
```

Another possible way would be to "override" the _id field, declaring it in the User schema, but then the _id won't be auto-generated, right? Is there any other approach to this issue?

**Comment by binrebin** [comment]
create a dump schema for example
```
class UserDumpSchema(User.schema.as_marshmallow_schema()):
    class Meta:
        fields = ['email']
```
this will dump only email field.

**Comment by lafrech** [comment]
You could declare a `load_only` id field. This one would replace the automatic id field.

```py
class User(Document):
    id = fields.ObjectIdField(dump_only=True, load_only=True, attribute="_id")
    email = fields.EmailField(required=True, unique=True)
```

If you want to use the unique required email as id, then ensure it is named _id in the collection and umongo won't create an id field.

```py
class User(Document):
    email = fields.EmailField(required=True, unique=True, attribute="_id")
```
