### ISSUE TITLE
no reference to document from instance method on EmbeddedDocument

### ISSUE THREAD

**Issue by otistamp** [Scille/umongo#218]
Unless I'm not seeing the reference, there is no way to access the parent document from inside an embedded document instance method without passing in the document when calling the function. This is particularly useful for integration objects but I'm sure there are benefits for other use cases.

for example:
```python
class EmbeddedIntegration(umongo.EmbeddedDocument):
    api_obj_id = fields.StringField()

    def downsync_current(self, doc):
        remote_obj = api.fetch_obj(self.api_obj_id)
        doc.name = remote_obj['name']
        doc.commit()
        return self

    def downsync_ideal(self):
        remote_obj = api.fetch_obj(self.api_obj_id)
        self.document.update({'name': remote_obj['name']})
        self.document.commit()
        return self

class Doc(umongo.Document):
    name = fields.StringField()
    integration = fields.EmbeddedField('EmbeddedDoc')

```

**Comment by lafrech** [comment]
Perhaps this ought to be done in a `Doc` method?

**Comment by lafrech** [comment]
This is not possible with umongo.

I suggest achieving this from the parent Document. (This probably means using `downsync_current`, which is not that bad.)

I'm not convinced this feature wouldn't be a substitute to good design.
