### ISSUE TITLE
Email field localization not working as expected

### ISSUE THREAD

**Issue by Gonzalo933** [Scille/umongo#222]
Hello,

This is a lengthy issue to reproduce, but I will try to upload some sample code over the weekend to reproduce the bug.

When using localizations of validation errors, there seems to be a bug with the Email field.

For example, in an Integer field, I correctly get "Not a valid integer" localized messages, but with the email field the error "Not a valid email address." does not get translated but "Field value must be unique." does.

It seems that the Email Validator is not calling the error_messages defined in [this line](https://github.com/Scille/umongo/blob/master/umongo/abstract.py#L156)

``
self.error_messages = I18nErrorDict(self.error_messages)
``

**Comment by lafrech** [comment]
Hard to fix without more details. Please provide a reproducible use case and I'll reopen.
