### ISSUE TITLE
Protecting Dict and List Fields between class instances

### ISSUE THREAD

**Issue by molten-firescar96** [Scille/umongo#223]
Generally python allows sharing of class attributes between instances of that class. But I don't think this this is the right behaviour for Umongo.

In this example the behaviour is expected, both instances of RegularClass share the `sharable_field` property.
```python
class RegularClass():
    primitive_field = None
    sharable_field = []
    @classmethod
    def create(cls, update):
        new_object = cls()
        new_object.sharable_field.append(update)
        new_object.primitive_field = update
        return new_object

a = RegularClass.create(update=1)
b = RegularClass.create(update=2)

print(a.primitive_field, a.sharable_field)
# 1 [1, 2]
print(b.primitive_field, b.sharable_field)
# 2 [1, 2]
```

But even though Umongo documents give the same output (when list fields have a default value), it's not what I expect.
```python
import motor
from umongo import Instance
from umongo.document import Document
from umongo.fields import ListField, IntField

db = motor.motor_asyncio.AsyncIOMotorClient()
instance = Instance(db.data)

@instance.register
class UmongoClass(Document):
    primitive_field = None
    sharable_field = ListField(IntField(), default=[])
    @classmethod
    def create(cls, update):
        new_object = cls()
        new_object.sharable_field.append(update)
        new_object.primitive_field = update
        return new_object

a = UmongoClass.create(update=1)
b = UmongoClass.create(update=2)

print(a.primitive_field, a.sharable_field)
# 1 [1, 2]
print(b.primitive_field, b.sharable_field)
# 2 [1, 2]
```
It's not what I expect because when I use SQLAlchemy or MongoEngine they do something different.

```python
import datetime
from mongoengine import *
connect('mydb')

class BlogPost(Document):
    sharable_field = ListField(IntField(max_length=50))
    
    @classmethod
    def create(cls, update):
        new_object = cls()
        new_object.sharable_field.append(update)
        return new_object

a = BlogPost.create(update=1)
b = BlogPost.create(update=2)


print(a.sharable_field)
# [1]
print(b.sharable_field)
# [2]
```
We've patched this for ourselves by automatically reinitializing dict and list fields. But this seems like it should be changed upstream. What do you think, could the constructor for DocumentTemplates initialize a different object for each instance? Here is our patch in the class that all of our documents implement.
```python
@classmethod
def create(cls,**kwargs):
    new_object = cls()
    for key, value in cls.schema.fields.items():
        if type(value) == ListField:
            new_object[key] = []
        if type(value) == DictField:
            new_object[key] = {}
```

**Comment by lafrech** [comment]
```py
sharable_field = ListField(IntField(), default=[])
```

Red flag. Mutable argument.

Use a callable instead.

```py
sharable_field = ListField(IntField(), default=list)
```

**Comment by molten-firescar96** [comment]
Okay, would it make sense for umongo to throw an error saying something like 

`Error: mutable argument "[]" is not allowed, try using "list" instead.`

implemented as `"Error: mutable argument {a} is not allowed, try using {b}  instead.".format(a=arg, b=type(arg))`

**Comment by lafrech** [comment]
This is not a umongo / marshmallow issue.

Search for "python pitfall mutable argument" on the internet.

There could be cases where people actually want to put a mutable here because they know what they're doing. Although this is very unlikely.

Anyway, this is a Python trick and it is not the responsibility of any lib to warn about it IMHO.

**Comment by molten-firescar96** [comment]
I understand and agree this is not required for python libraries to implement. This isn't a bug report, it's more of a feature request. I noticed a couple other Database connectors (SQLAlchemy and MongoEngine) have chosen to do solve the python pitfall.

If I made a PR would you be interested?

**Comment by lafrech** [comment]
I didn't know they did. Your example doesn't show it because you don't pass the default. I don't have time right now to go fond out how they do.

Thanks for the PR proposal but I'm reluctant to do this in umongo. That would be in marshmallow. 

And even then, as a marshmallow maintainer, I don't think we want to address this in marshmallow either. Our stance is that the use case is easily achieved by using a callable and passing a mutable argument to a method is a mistake in the first place.

**Comment by molten-firescar96** [comment]
I uploaded the wrong version, here is the equivalent code in MongoEngine. If it would be helpful I'm happy to make a minimum reproducible build for SQLAlchemy (or another library) as well.

```python
import datetime
from mongoengine import *
connect('mydb')

class BlogPost(Document):
    sharable_field = ListField(IntField(max_length=50), default=[])
    
    @classmethod
    def create(cls, update):
        new_object = cls()
        new_object.sharable_field.append(update)
        return new_object

a = BlogPost.create(update=1)
b = BlogPost.create(update=2)

print(a.sharable_field)
# [1]
print(b.sharable_field)
# [2]
```

Okay, for our own development we need to protect against interns making this mistake so we will continue using either the patch I referenced above or something more explicit. I think we'll be okay if umongo/marshmallow doesn't change.

**Comment by lafrech** [comment]
Thanks.

> If it would be helpful I'm happy to make a minimum reproducible build for SQLAlchemy (or another library) as well.

No, don't bother.

Whatever patch you come up with, please share it here in case someone wants to do the same.
