### ISSUE TITLE
createdAt and updatedAt timestamp

### ISSUE THREAD

**Issue by shaozi** [Scille/umongo#237]
Is there a way to add automatically updated timestamps `createdAt` and `updatedAt` to a collection?

**Comment by lafrech** [comment]
Declare the fields then use [pre_insert](https://umongo.readthedocs.io/en/latest/apireference.html#umongo.document.DocumentImplementation.pre_insert) and [pre_update](https://umongo.readthedocs.io/en/latest/apireference.html#umongo.document.DocumentImplementation.pre_update) callback to update them.

**Comment by shaozi** [comment]
Can you give me an example? The document is kind of simple...

**Comment by shaozi** [comment]
I figured out:

```python
class BaseDocument(Document):
    createdAt = fields.DateTimeField(required=False)
    updatedAt = fields.DateTimeField(required=False)
   
    def pre_insert(self):
        self.createdAt = datetime.now(timezone.utc)

    def pre_update(self):
        self.updatedAt = datetime.now(timezone.utc)
```
Can we add an example to the user guide document?

**Comment by lafrech** [comment]
That's it.

Except the code you write executes the datetime.now call at import time.

You should pass a callable (it can be a lambda).

I guess we could add this as an example in the docs. No time for this right now but sure.

**Comment by shaozi** [comment]
Since timestamp is so common, is it possible to use a decorator to add the timestamp?

```python
@timestamp
@instance.register
class A(Document):
    name = fields.StrField()

@timestamp
@instance.register
class B(Document):
    name = fields.StrField()
```

Then A and B will all have timestamps.

**Comment by lafrech** [comment]
Well, I haven't been giving this much thought, but I guess you could do that. It would look nice. This might belong to user code but it would be nice to share it if you do it.

Be sure to call super().pre_update in pre_update no avoir shadowing a pre_update method in the class. And likewise for pre_insert.

I'd put the decorator between instance.register and class definition.

**Comment by shaozi** [comment]
hmm.. I just starts to learn python decorator, maybe on a totally wrong path, but here is what I do:

```python
def add_timestamp(doc_class):
    """
    Decorator to add `createdAt` and `updatedAt` to
    a document class. And use pre_insert and pre_update to 
    update them
    
    """
    doc_class.createdAt = fields.DateTimeField(required=False)
    doc_class.updatedAt = fields.DateTimeField(required=False)

    def __add_create_timestamp(doc):
        doc.createdAt = datetime.now(timezone.utc)
    def __add_update_timestamp(doc):
        doc.updatedAt = datetime.now(timezone.utc)
    
    doc_class.pre_insert = __add_create_timestamp
    doc_class.pre_update = __add_update_timestamp
    return doc_class

@instance.register
@add_timestamp
class Users(Document):
    username = fields.StrField()

@instance.register
@add_timestamp
class Comments(Document):
    user = fields.ReferenceField(Users)
    comment = fields.StringField(required=True)

```

Don't know how to call super in the decorator though.

**Comment by lafrech** [comment]
- Use a callable as default value
- Don't shadow doc._pre_... methods. Call them in your new methods.

I think I would have done this using `@functools.wraps` and a subclass but it might work your way.

**Comment by shaozi** [comment]
I don't understand what do you mean by the two bullet points, can you elaborate?

**Comment by lafrech** [comment]
Forget the comment about using a callable. It applies when using datetime.now as default value, not the way you call it. Sorry for the confusion. This is a regular issue and I overlooked your message.

The comment about shadowing methods is also wrong, actually. When using a pre_commit/pre_insert method in a document, I always call the method from the parent to avoid overriding it. Even if it does not exist yet, as it may happen in the future. Since you do this in the BaseDocument, you don't really need to do that, as it is unlikely that Document will be added default implementations to these.

I hope I'm clear. Sorry for the confusion I've brought.

Your base document looks fine.

```py
class BaseDocument(Document):
    createdAt = fields.DateTimeField()
    updatedAt = fields.DateTimeField()
   
    def pre_insert(self):
        self.createdAt = datetime.now(timezone.utc)

    def pre_update(self):
        self.updatedAt = datetime.now(timezone.utc)
```

If you want this on a subset of your documents, you may declare an abstract TimestampDocument for this.

```py
class TimedDocument(BaseDocument):
    class Meta:
        abstract = True

    createdAt = fields.DateTimeField()
    updatedAt = fields.DateTimeField()
   
    def pre_insert(self):
        self.createdAt = datetime.now(timezone.utc)

    def pre_update(self):
        self.updatedAt = datetime.now(timezone.utc)
```

I meant wrap the decorated class in a new class overriding the methods. But don't bother, the method above using a base document class works fine.
