### ISSUE TITLE
how to use update_one in motor?

### ISSUE THREAD

**Issue by shaozi** [Scille/umongo#238]
Motor has `update_one()` and `replace_one()`. How do I invoke those on a collection?

**Comment by shaozi** [comment]
closest thing I can find is to do a `document.commit()`. However, that what should I do if I want to do `$inc` ?

**Comment by momocow** [comment]
`YourDocumentClass.collection` is a collection object from your db driver, that is, motor, directly call `update_one()` and `replace_one()` on the collection object.

**Comment by lafrech** [comment]
umongo does not deal with this but does expose collection as mentioned in https://github.com/Scille/umongo/issues/238#issuecomment-618929285 so you can do it from here just like you'd do it with the raw driver.
