### ISSUE TITLE
Converting aggregation results to umongo objects

### ISSUE THREAD

**Issue by martinjuhasz** [Scille/umongo#27]
I'm using umongo to gather documents using mongos aggregation framework:

```
MyDocumentClass.collection.aggregate([
            {'$match': {
                'field1': value1,
                'field2': value2
            }},
            # more pipes
        ])
```

The resulting documents are plain dictionaries. It wouldn't be that bad since i want to convert them to json for serving over an api anyway, but i loose umongos nice integration for `dump()` that way and i would have to convert objectIDs, Dates etc myself.

My current solution is iterating over the results and converting them into my desired umongo Class

```
raw_docs = await above_future.to_list(None)
docs = [MyDocumentClass.build_from_mongo(docs) for docs in raw_docs]
```

Is there a better way to do this or what is your recommended solution for converting aggregate results to umongo Document objects (i can totally see why you wouldn't do this automatically since aggregation results don't have to be anyway structured like modeled Document classes)?

**Comment by touilleMan** [comment]
Hi,

umongo doesn't provide anything around mongodb's aggregation.
As you said, the result of the aggregation can be very different to the orginal document so I think it would be really tricky and bug prone to dynamically create a class for the result of the aggregation.

The recommanded way with umongo is to customize the document's marshmallow schema:

```python
from umongo import Document, fields, Instance, Schema
from pymongo import MongoClient


db = MongoClient().test
instance = Instance(db)


@instance.register
class MyDoc(Document):
    age = fields.IntField()
    name = fields.StrField()
    class Meta:
    	collection_name = 'test'


class AggregatedSchema(Schema):
    _id = MyDoc.schema.fields['name']
    age = fields.ListField(MyDoc.schema.fields['age'])


aggregation = MyDoc.collection.aggregate([
            {'$match': {'age': {'$lt': 15}}},
            {'$group': {'_id': '$name', 'age': {'$push': '$age'}}}
        ])


schema = AggregatedSchema()
for x in aggregation:
	print(schema.dump(x).data)
```

**Comment by martinjuhasz** [comment]
hah. this totally fits my needs. thanks!

also thanks for maintaining umongo. i find it a perfect fit between my application code and mongodb. not relying on a driver implementation really does the trick for me.

**Comment by touilleMan** [comment]
You're welcome, it's always a pleasure to build something that helps people :+1:

**Comment by martinjuhasz** [comment]
After using umongo now for several days my need for this didn't drift away.

I'm often using mongodb's aggregation pipeline for various filtering or [sampling](https://docs.mongodb.com/manual/reference/operator/aggregation/sample/) on a collection, which can not be done using normal find method. The resulting documents are the same as the collection documents.

My Problem now is that i have to define a `Document` subclass if i want to use umongos abstraction and another `Schema` subclass, thats nearly the same, for using aggregation. Resulting problems when doing this are inconsistences f.e. my ID field is called `id` on umongo and `_id` on marshmallow schemas.

**Comment by touilleMan** [comment]
> My Problem now is that i have to define a Document subclass if i want to use umongos abstraction and another Schema subclass, thats nearly the same, for using aggregation. Resulting problems when doing this are inconsistences f.e. my ID field is called id on umongo and _id on marshmallow schemas.

I don't get the trouble: given the result of your aggregation is the document itself why your first solution doesn't work anymore ?
```python
raw_docs = await above_future.to_list(None)
docs = [MyDocumentClass.build_from_mongo(docs) for docs in raw_docs]
```

Beside, I think we can make thing more elegant for your needs by adding a `bind_as` attribute to the `aggregate` function in order to do the construction of the `Documents` inside the returned cursor:

```python
@instance.register
class AggregatedObj(EmbeddedDocument):
    field1 = fields.StrField()
    field2 = ...

results = MyDocumentClass.collection.aggregate([
            {'$match': {
                'field1': value1,
                'field2': value2
            }},
            # more pipes
        ], bind_as=AggregatedObj)

(await results.to_list(None))[0]
# <object EmbeddedDocument __main__.AggregatedObj({'field1': ...})>
```

What do you think ?

**Comment by martinjuhasz** [comment]
I think this is a considerable option.  I'm not sure if this is is a core function that umongo should provide or if i'm just to lazy to cast aggregation results into umongo objects. For now i'm going with `build_from_mongo`. What do you think?

**Comment by ribx** [comment]
What I did was:

```python
class AggregateSchema(MyDocumentsClass.schema.as_marshmallow_schema(mongo_world=True)):
    class Meta:
        pass

results, error = AggregateSchema(many=True).dump(MyDocumentsClass.collection.aggregate(pipeline))

**Comment by lafrech** [comment]
Closing this as

> the result of the aggregation can be very different to the orginal document
