### ISSUE TITLE
Missing to_raise=AttributeError parameter in EmbeddedDocumentImplementation's __*attr__ methods?

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#28]
Isn't there a `to_raise=AttributeError` parameter missing in the `__getattr__`, `__setattr__` and `__delattr__` methods of `EmbeddedDocumentImplementation`?

https://github.com/Scille/umongo/blob/master/umongo/embedded_document.py#L92

Like in `DocumentImplementation`:

https://github.com/Scille/umongo/blob/06eed171d1338bc72f95b36091e69aac093f489f/umongo/document.py#L240

**Comment by touilleMan** [comment]
Good catch :+1:
