### ISSUE TITLE
How would you model a many to many relationship using references with uMongo?

### ISSUE THREAD

**Issue by nmcbride** [Scille/umongo#280]
Hello all,

I'm trying to get my head around using the ReferenceField by implementing common patterns used in mongo. I'm getting stuck though when I try to code a two way relationship using the ReferenceField. Originally I thought it would be something simple like this:

```python
class Book(Document):
    authors = ListField(ReferenceField(Author))
    
    class Meta:
        collection_name = "books"
        
class Author(Document):
    books = ListField(ReferenceField(Book))
    
    class Meta:
        collection_name = "authors"
```

However no matter how I code it I cannot get it to work. The two classes can't be in the same file as the first wont know about the second and even when I put them into their own files I get circular import errors. I know circular imports are allowed in python and I can do other circular import with regular classes in test files but it seems like for this specifically it wont work.

Is there another way to do a many to many relationship?

Thanks very much.

**Comment by nmcbride** [comment]
So I can get it to work if I use a GenericReferenceField. I'm not sure if that's the correct way to do this though. Would you mind taking a look at the below and seeing if I am setting up the model correctly and if I am using it correctly? I feel like there should be a better way than saving the author twice in this example but perhaps not.  Thanks for your input.

```python
@instance.register
class Author(Document):
    name = StrField(required=True, unique=True)
    books = ListField(GenericReferenceField)

    class Meta:
        collection_name = "authors"


@instance.register
class Book(Document):
    title = StrField(required=True)
    authors = ListField(GenericReferenceField, required=True)

    class Meta:
        collection_name = "books"


async def build_lots():
    await Author.collection.drop()
    await Author.ensure_indexes()

    await Book.collection.drop()
    await Book.ensure_indexes()

    i = 0
    n = 0
    for _ in range(randint(1, 100)):
        new_author = Author()
        new_author.name = f'Author{i}'
        await new_author.commit()

        books = []

        i += 1

        for _ in range(randint(1, 3)):
            new_book = Book()
            new_book.title = f'book{n}'
            new_book.authors = [new_author]
            await new_book.commit()

            books.append(new_book)

            n += 1
        n = 0

        new_author.books = books
        await new_author.commit()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(build_lots())
```

Thanks very much.

**Comment by lafrech** [comment]
Sorry for the delay.

It should work by passing document names as strings, doesn't it?

```py
class Book(Document):
    authors = ListField(ReferenceField("Author"))
    
    class Meta:
        collection_name = "books"
        
class Author(Document):
    books = ListField(ReferenceField("Book"))
    
    class Meta:
        collection_name = "authors"
```
