### ISSUE TITLE
Value to return by document.get('field') when field is missing in DB/data_proxy

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#29]
I'm opening a dedicated issue for this topic, to follow up on https://github.com/Scille/umongo/pull/23.

Currently, when a value is missing in the data proxy, `None` is returned:

```py
    def get(self, name, to_raise=KeyError):
        if name not in self._fields:
            raise to_raise(name)
        field = self._fields[name]
        name = field.attribute or name
        value = self._data[name]
        if value is missing:
            if self.partial:
                raise FieldNotLoadedError(name)
            elif field.default is not missing:
                return field.default
            else:
                return None
        return value
```

@touilleMan:

> The use of None is always slippy given you never know what it really means.
>
> The policy in umongo is to say "None is None", so if you want to set a field to None you must have set allow_none=True in your field config.
>
> Only exception is the fields that are missing in the database which are represented to the user as None given comparing against a missing object would be to cumbersome (thus we could make the missing value configurable and None by default).

Another option is to raise an exception, just like any `dict` would do when a value is missing. The advantage of this is that it always respects the difference between `None` and "no value". But it is less practical to manage (need to cath the exception or call get with a default value).

So there's a trade-off here between ease of use and absolute data integrity.

@touilleMan's proposal is that in most cases, `None` is equivalent to "no value", so let's keep things simple, and for users who really needs to make a difference, introduce a feature allowing to specify another default value.

Maybe we could expend this last feature by allowing the user to ask for an exception to be raised rather than a return value.

I have no definitive opinion about this. I'm just trying to summarize the options.

Another consequence of this choice: when serializing a Document using `shema.dump(document)`, the value returned by `document.get` (`None` or another default value) will appear in the dump. If `get` returns an Exception, however, the field disappears from the dump. Right now, I like this behavior (it allows my API to only return values that are in database), but I don't have the expertise to tell if it is the best. And anyway, maybe it is the user's problem and it shouldn't be taken into account by umongo.

**Comment by lafrech** [comment]
I'm facing another issue which might be related.

I want to delete a field from a document. It has currently no value (`missing` in data_proxy), but I'm not supposed to know that and if I call `get`, I get `None`, which does not tell me whether it it really `None` or missing.

If I call

```py
    del document.field
```
I get an exception because [delete checks if the field is missing](https://github.com/Scille/umongo/blob/master/umongo/data_proxy.py#L149)

```py
        if self._data[name] is missing:
            raise to_raise(name)
```

And I can't do 

```py
    if hasattr(document.field):
        del document.field
```
because `hasattr` returns `True` because `getattr` returne `None`.

To reliably remove it, I could do:

```py
    document.field = None
    del document.field
```

or

```py
    try:
        del document.field
    except AttributeError:
        pass
```

but both solutions are out in terms of simplicity.

If we derogate to the "missing -> Exception when calling `get`" rule for practical reasons, it would make sense to also derogate in `delete` and not raise an error if calling `delete` on a missing field.

(And as a sidenote, I've been trying the "`missing` -> `Exception`" approach and I admit it is a bit of a hassle to call `hasattr` twice per line of code, so I'm beginning to understand the `missing` -> `None` derogation...)

**Comment by touilleMan** [comment]
I've been working on this, here is my conclusion:
- `DataProxy` (the internal class accessible through `my_doc._data`) always returns the real state inside the database. So if `my_doc._data.get('my_field')` retuns `None` is not equivalent of returning `missing`
- `Document` and `EmbeddedDocument` wrap the `DataProxy` and return `None` in both case given it's what you would expect
- Advanced user who want to have higher control should pick inside the `_data` field directly
- I didn't add an option to define what the Document should return when `missing` is found given this option should be passed to `EmbeddedDocument` children, which can be used by different `Document` with different option.
- You can do `del my_doc.my_field` many times without error

**Comment by touilleMan** [comment]
see 91d66bdce8f1ff9bde7f77b3d0b3de68cc89d5cb

**Comment by lafrech** [comment]
This looks fine to me.

Besides, it will never be to late (it wouldn't break the logic) to 

- either wrap `my_doc._data.get()` into something like `my_doc.get(missing=whatever)` to receive something else than None (or even raise an exception)
- or just ask `get` to pass `missing`

For instance:

```py
    # Data-proxy accessor shortcuts
    def __getitem__(self, name, missing=None):
        value = self._data.get(name)
        return value if value is not data_proxy.missing else missing
```

or 

```py
    # Data-proxy accessor shortcuts
    def __getitem__(self, name, pass_missing=False):
        value = self._data.get(name)
        return value if (value is not missing or pass_missing) else None
```

Thanks.
