### ISSUE TITLE
Is this possible to inheriting umongo classes

### ISSUE THREAD

**Issue by SQWiperYT** [Scille/umongo#291]
I have a class with soo many fields, I want to inherit it, is it possible?

**Comment by lafrech** [comment]
Not sure what you mean.

Sure you can inherit umongo Document and EmbeddedDocument.

https://umongo.readthedocs.io/en/latest/userguide.html#inheritance

https://umongo.readthedocs.io/en/latest/userguide.html#object-oriented-world
