### ISSUE TITLE
How to created a capped collection

### ISSUE THREAD

**Issue by binrebin** [Scille/umongo#292]
See I need a collection with a single document to store counters for all collections. Mongodb docs [https://docs.mongodb.com/manual/core/capped-collections/](Docs) says `capped` collections canbe created with a high-throughput. How can I do this with Umongo Document class. Here is my model.

```
class Counter(Document):
    _id = fields.ObjectField()
    notify_counter = fields.NumberField()
    memberid_counter = fields.NumberField()
    class Meta:
        indexes = ['notify_counter', 'memberid_counter']
```

**Comment by binrebin** [comment]
@lafrech, could you help, please..

**Comment by lafrech** [comment]
There is no specific support for this in umongo.

You can do that directly from your DB driver. For instance, for pymongo, see https://pymongo.readthedocs.io/en/stable/api/pymongo/database.html#pymongo.database.Database.create_collection.

We could try to wrap this feature in umongo but it wouldn't have much added value so I don't think it is worth the added API surface.

**Comment by binrebin** [comment]
@lafrech , thanks for your help. I gave up that idea. new workaround tried. If you add this. Helpful for somebody or for me atfuture time

**Comment by lafrech** [comment]
Lets keep things simple now. The user can do this through the DB driver lib.
