### ISSUE TITLE
TypeError: 'Database' object is not iterable

### ISSUE THREAD

**Issue by stefaneidelloth** [Scille/umongo#336]
I tried to follow the "Quick example".

I got an error **'Database' object is not iterable**. 
How can I resolve it? I use python 3.8.5, pymongo 3.10.1 and MongoDB 4.4.2.

![image](https://user-images.githubusercontent.com/12675339/104003574-dc72e080-51a2-11eb-8143-81b93e8e1714.png)

**Comment by voodoonofx** [comment]
This is true and valid for 2.3, but 3.0 uses the currently documented syntax.

**Comment by lafrech** [comment]
Yes, looks like you're using an old umongo version.
