### ISSUE TITLE
Mix fields types in a ListFields

### ISSUE THREAD

**Issue by luckystar1992** [Scille/umongo#359]
How to define a field with list types( array in MongoDB), but items in this list may have different types. For example:
```
1.[1, "one", "two"]
2.["I", 1, "II", 2, "III", 3]
```

**Comment by luckystar1992** [comment]
@Aman-14 Thanks a lot. Is there any course or project that can provide more helpful usage?

**Comment by Aman-14** [comment]
There are not much examples out there but you can refer examples folder. It has some basic examples that will help you getting started.
