### ISSUE TITLE
pymongo Database class explicitly denies bool

### ISSUE THREAD

**Issue by whophil** [Scille/umongo#365]
In pymongo >= 4, the `Database` class denies usage as bool. This was introduced with 
https://github.com/mongodb/mongo-python-driver/pull/728

This breaks https://github.com/Scille/umongo/blob/28168d67f1c0a5030b65da1717859bd7c3a0bba0/umongo/instance.py#L136, and perhaps other lines.

Workaround is to use pymongo < 4 until fixed here.

**Comment by lafrech** [comment]
True. Would you like to send a fix PR?

**Comment by whophil** [comment]
> True. Would you like to send a fix PR?

Will do, when I get a moment. But I won't be offended if somebody beats me to it 🙂

**Comment by lafrech** [comment]
Closed by #366.

Thank you for your contributions.

I just sent you an invitation to join the maintenance team. No pressure to do any more work but if you have things you'd like to improve, here are the keys.
