### ISSUE TITLE
Passing marshmallow Schema options to the models

### ISSUE THREAD

**Issue by pedropregueiro** [Scille/umongo#383]
Hi there, I wanna use the marshmallow `exclude` and `dump_only` fields available in their [Schema](https://marshmallow.readthedocs.io/en/stable/api_reference.html?highlight=exclude#marshmallow.Schema) to remove some fields from the end result of `dump()`.

Is there a way to easily do this today?

Ideally something like this:

```
@instance.register
class User(Document)
    name = fields.StrField()
    secret = fields.StrField()

    class Meta:
        exclude = ["secret"]
```

**Comment by benkaufman1757** [comment]
I think `load_only` might be what you are looking for. Here is a test case you can trying running and messing around with. Requires pymongo_inmemory so you don't have to have a mongodb instance running -- `pip install pymongo_inmemory`
```
from umongo import Document, fields
from umongo.frameworks import PyMongoInstance
from pymongo_inmemory import MongoClient

def test_case() -> None:
    db = MongoClient().test
    instance = PyMongoInstance(db)

    @instance.register
    class User(Document):
        name = fields.StrField()
        secret = fields.StrField(load_only=True)

    test_user = User(name="Tony", secret="muskrat")
    test_user.commit()
    assert "secret" not in test_user.dump()

    # search User collection, not using test_user.reload() in this case to make it clear it's coming back from the database
    reloaded = User.find_one({})
    assert reloaded.name == "Tony"
    assert reloaded.secret == "muskrat"
    assert "secret" not in reloaded.dump()

if __name__ == "__main__":
    test_case()
```

**Comment by pedropregueiro** [comment]
thanks @benkaufman1757, this is exactly what I was looking for!
