### ISSUE TITLE
pymongo: UnboundLocalError when committing unmodified Document

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#39]
To reproduce, you may for instance duplicate [this line](https://github.com/Scille/umongo/blob/master/tests/frameworks/test_pymongo.py#L64) in the tests to commit a Document twice in a row:

```py
    def test_create(self, classroom_model):
        Student = classroom_model.Student
        john = Student(name='John Doe', birthday=datetime(1995, 12, 12))
        ret = john.commit()
        ret = john.commit()
```

The problem is in [commit()](https://github.com/Scille/umongo/blob/master/umongo/frameworks/pymongo.py#L66):

    self.is created = True
    payload = None

then `ret` is assigned no value before `return ret`.

**Comment by touilleMan** [comment]
Good report, fix is here: ba92171
