### ISSUE TITLE
EmbeddedDocument inheritance

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#54]
Currently, only `Document` supports inheritance. `EmbeddedDocument` inheritance should be covered as well.

I could try to have a go at it, although I'm not sure when and how difficult it would be. It impacts the core of umongo.

@touilleMan, do you have any advice? Is it something you'd rather do yourself?

**Comment by touilleMan** [comment]
I start evaluating the difficulty for this one and... well let say it was easier than I thought !
enjoy 26ff4b8df7b007386d31ef4c9ae94ad2584dcbb6 ;-)

**Comment by lafrech** [comment]
I was about to send you my poor attempt and was notified of merge conflicts since you had committed this 4 minutes before...

https://github.com/Scille/umongo/compare/master...Nobatek:dev_embedded_doc_inheritance?expand=1

Thanks!
