### ISSUE TITLE
abstract and allow_inheritance in EmbeddedDocument inheritance

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#58]
It seems Meta attributes abstract and allow_inheritance have no effect in EmbeddedDocument. Indeed, they do not appear in EmbeddedDocumentOpts.

There is no collection consideration involved, but still a model may need to have abstract `EmbeddedDocument`s that are not meant to be instantiated, only subclassed. And one may want to only allow inheritance on some embedded documents.

I think I addressed those in [my PR](https://github.com/Scille/umongo/compare/master...Nobatek:dev_embedded_doc_inheritance#diff-16b8e114ff7e011dbfb931148c2222aeR41) since I copied a lot (maybe too much) from `Document`.

**Comment by touilleMan** [comment]
e062ab05f6c7f50e8ffd7ad86890eb8cf0e673db :+1:
