### ISSUE TITLE
async / await style

### ISSUE THREAD

**Issue by imbolc** [Scille/umongo#6]
Hi :)

`MotorAsyncIODal.commit` doesn't work with await syntax. I think it's better to rewrite all async code in 3.5 style, nobody care about 3.4. Thanks for great lib! Do you have power for docs?

**Comment by touilleMan** [comment]
Hi,

> `MotorAsyncIODal.commit` doesn't work with await syntax
Thanks for the report, I've fixed this in 5fdfada3148bdcdf0fa7f324a9bef1d1845dc88b ;-)

> I think it's better to rewrite all async code in 3.5 style, nobody care about 3.4

I would prefer supporting Python 3.4 given it's the [version provided by Debian stable](https://packages.debian.org/search?keywords=python3). Beside the code involved is pretty small (~250 lines for motor-asyncio) so it seems easy to maintain the "crappy syntax".

> Do you have power for docs?

I didn't get what you meant... I'm writing the docs here http://umongo.readthedocs.org/en/latest/?badge=latest and I can take any help you offer ! \\^^/

**Comment by imbolc** [comment]
Sorry I just didn't notice the docs badge.
Now awaits work nice, thanks a lot :)
