### ISSUE TITLE
Pass meta attributes to schema in as_marshmallow_schema

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#65]
Not sure whether this is a feature request or a question.

I would like to exclude a field from a schema of an `EmbeddedDocument` when calling `as_marshmallow_schema` on its container `Document`.

To do that on a Schema generated by `as_marshmallow_schema`, I would just call `as_marshmallow_schema` to get the Schema then subclass it to add a Meta class:

``` py
schema = Doc.as_marshmallow_schema()

class MySchema(schema):
    class Meta:
        exclude: ('hidden_field',)
```

It would be cool to be able to call 

``` py
schema = Doc.as_marshmallow_schema(meta={'exclude': ('hidden_field',)})
```

but it's not critical, at least in my current use of umongo.

It becomes more useful if the Schema I need to modify is nested in the document, so that the call to `as_marshmallow_schema` is not direct but cascaded through `EmbeddedField`. In this case, the meta attributes need to be provided to `as_marshmallow_schema` by `as_marshmallow_field` in 
`EmbeddedField`.

Maybe it could take the (absolutely untested) following form:

``` py
    # In BaseSchema
    def as_marshmallow_schema(self, params=None, base_schema_cls=MaSchema,
                              check_unknown_fields=True, missing_accessor=True,
                              mongo_world=False, meta=None):

        [...]
        if meta is not None:
            # Do what is to be done

    # In EmbeddedField
    def as_marshmallow_field(self, params=None, mongo_world=False):
        # Overwrite default `as_marshmallow_field` to handle nesting
        kwargs = self._extract_marshmallow_field_params(mongo_world)
        if params:
            nested_params = params.pop('params')
            nested_meta = params.pop('meta')
            kwargs.update(params)
        else:
            nested_params = None
            nested_meta = None
        nested_ma_schema = self._embedded_document_cls.schema.as_marshmallow_schema(
            params=nested_params, mongo_world=mongo_world, meta=meta)
        return ma_fields.Nested(nested_ma_schema, **kwargs)
```

Or am I missing an already existing feature?

**Comment by touilleMan** [comment]
I like this very much ! It is simple to implement and really get rid of the boilerplates

Now I'm waiting for you PR ;-)
