### ISSUE TITLE
EmbeddedDocument inheritance: GrandChild can't be used as Parent

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#66]
While trying to create a test case for https://github.com/Scille/umongo/pull/56#issuecomment-257822362, I think I found another (unrelated) issue.

In [`test_embedded_inheritance`](https://github.com/Scille/umongo/blob/master/tests/test_fields.py#L318):

```py
        # Test child can be passed as parent
        # This passes
        MyDoc(parent={'cls': 'EmbeddedChild', 'a': 2})

        # Test grandchild can be passed as parent
        # This fails
        MyDoc(parent={'cls': 'GrandChild', 'd': 2})
        # Is this due to a recursion issue in embedded_document_cls.opts.children?
        # This fails as well
        assert 'GrandChild' in EmbeddedParent.opts.children
```

Either `embedded_document_cls.opts.children` should know about its grandchildren, either the test in `EmbeddedField._deserialize` should be recursive.

**Comment by touilleMan** [comment]
I've started working on a fix for this on this weekend, this should be fixed shortly

**Comment by touilleMan** [comment]
dc9d3bb enjoy !
