### ISSUE TITLE
pymongo in requirements

### ISSUE THREAD

**Issue by imbolc** [Scille/umongo#7]
I'm not sure, but maybe it's better to remove `pymongo` from requirements.
Now if I do `pip install umongo -U`, it upgrades pymongo to latest 3.2.2 version.
But motor requires `pymongo==2.8.0`, so I have to reinstall it after that.

**Comment by touilleMan** [comment]
`pymongo` deps is needed no matter what given we use `bson` package. See #5 for more informations.

To make things more explicit, I'm thinking about doing extra install options to install driver along with umongo like that:
```shell
pip install umongo[pymongo]
pip install umongo[txmongo]
pip install umongro[motor]
```

What do you think ?

**Comment by imbolc** [comment]
It looks clear for me, thanks

**Comment by touilleMan** [comment]
enjoy fe155c6ad3002badbdea972201c9729373bcf9d2 ^^

**Comment by imbolc** [comment]
Thanks :)
