### ISSUE TITLE
Can mongo_world=True work with missing_accessor=True?

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#73]
AFAIU, in `as_marshmallow_schema`, one can pass 

    missing_accessor=True, mongo_world=True

But it is bound to fail, because `schema_from_umongo_get_attribute` expects `obj` to be an object, not a `dict`.

```py
def schema_from_umongo_get_attribute(self, attr, obj, default):
    ret = MaSchema.get_attribute(self, attr, obj, default)
    if ret is None and ret is not default and attr in obj.schema.fields:
        raw_ret = obj._data.get(attr)
        return default if raw_ret is missing else raw_ret
    else:
        return ret
```

Shouldn't this be prevented? Like, by setting `missing_accessor` to `False` when `mongo_world is True`?

**Comment by lafrech** [comment]
Simple fix in `as_marshmallow_schema`:

```py
        if missing_accessor and not mongo_world:
            nmspc['get_attribute'] = schema_from_umongo_get_attribute
```

**Comment by touilleMan** [comment]
I'm wondering if we should not instead remove the `missing_accessor` instead, then using only `schema_from_umongo_get_attribute` when `mongo_world` is `False`.
This way the behavior should be the same than the direct access of de `obj._data` field when `mongo_world` is `True`.

Do you think I missed a usecase with this ?

**Comment by lafrech** [comment]
If you remove `missing_accessor` parameter and consider `not mongo_world` instead, you prevent the `mongo_world is True and missing_accessor is True` case, which is right, at least as long as it is broken.

You also forbid the `mongo_world is False and missing_accessor is False` case.

I'm not sure I get the whole picture about that `schema_from_umongo_get_attribute` feature. From what I understand looking at the tests, its only use is to let the object return `missing` and therefore remove the attribute from serialized data rather than returning `None`. This is useful to me and I can remember myself complaining, when this feature was missing, about all the `None` fields in my API output when data was missing in DB. I don't think of a use case where I would want to opt out, so I guess it is fine to not over-parametrize and just keep `mongo_world`.

I'm also realizing that I might lack this feature when serializing data from Mongo world. It makes output a bit different depending on the path used (directly from DB or through OO world).

Currently, `schema_from_umongo_get_attribute` is broken in Mongo world because it seeks the umongo schema and data proxy in the object. What if the umongo schema was stored somewhere in the marshmallow schema. Couldn't `schema_from_umongo_get_attribute` figure out something with that schema and the raw data? This way, it could work in Mongo world as well, right?

To summarize, we have two independent points here:

- Should and can that feature work in Mongo world? If some day the feature is extended to work in Mongo world, it will be a "breaking" change since it will slightly modify the output, but no big deal.

- Should it be forced or parametrized? I'm not sure about the parameter. Today, I don't see the use case for opting out, but maybe someone would. I can't tell. If we keep the parameter, we just need to make sure the doc is clear about the implications. I must admit it's a bit blurry to me and I had to peek in the code and tests. For now, we might as well remove the parameter as it is broken anyway (https://github.com/Scille/umongo/issues/74). Let's not make things too complicated. If someone asks, it's never too late to put it back and fix its propagation.

**Comment by touilleMan** [comment]
> I'm also realizing that I might lack this feature when serializing data from Mongo world. It makes output a bit different depending on the path used (directly from DB or through OO world).

Mongo world is supposed to always return you the raw data, so there is no need to provide a custom `get_attribute`. Thus Mongo world and OO world should provide the same consistent behavior (i.e. `missing` is handled by marshmallow-pure schema)

> Currently, schema_from_umongo_get_attribute is broken in Mongo world

As stated above: it is not broken, it is not needed 😄 

Given your summarize, I think we agree `missing_accessor` is doing more harm than good so I pushed a new version removing it. Beside, this feature should work with Mongo world as well as OO world, so open an issue if it's not the case 👍

**Comment by lafrech** [comment]
OK, I get it. Removing it is the right thing to do.

Thanks.
