### ISSUE TITLE
How to you test an app?

### ISSUE THREAD

**Issue by mindojo-victor** [Scille/umongo#77]
We have a web app which uses MongoDB via MongoEngine. In our tests we using https://github.com/theorm/mongobox to start a MongoDB instance on a port before the tests start, then before each test method (we are using `unittest`) all the collections and databases are dropped. It works for us.

But I see that Mongobox is not developing and has some not fixed bugs. This makes me to think that other people use something different in their tests.

I've seen mentions of mongomock ( http://docs.mongoengine.org/guide/mongomock.html ) but I'd like to use a real MongoDB instance in our tests.

What do you use?

**Comment by lafrech** [comment]
(Didn't you mean to post this question in MongoEngine's bugtracker? Anyway, it is ODM-independant.)

In my team, we develop on our workstations in a VM and we have a MongoDB instance running in the VM. The automated tests (pytest) use that instance on a test database using a fixture that drops the base before each test.

So just like you except MongoDB is always running.

Never heard of Mongobox.

**Comment by mindojo-victor** [comment]
I didn't post to MongoEngine, because from my experience they don't respond quickly if at all.

**Comment by lafrech** [comment]
OK, no problem. Just asking because this is a general question and there are (currently) many more users there.

Things are moving in MongoEngine thanks to a new maintainer.
