### ISSUE TITLE
Issue passing a missing value to a ListField

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#78]
Current code:

```py
class ListField(BaseField, ma_fields.List):

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('default', [])
        kwargs.setdefault('missing', lambda: List(self.container))
        super().__init__(*args, **kwargs)
```

If I put this in my model

    test = fields.ListField(
        fields.IntField(),
        missing=[1,2,3])

then when instantiating my `Document`, I end up with a `list` instead of a umongo `List`, which is not good. For instance, when appending to the list, `document.is_modified()` returns `False`. There may be other consequences.

Is the user expected to import umongo's `List` and feed this to the field (not sure it actually works)? From a user perspective, since setting a default anything other than a `List` is pretty dangerous, maybe there should be a safeguard, here.

Or should we sort of cast `missing` to `List` in the `__init__`? Not so obvious as `List([1,2,3])` or `List(container, [1,2,3])` won't work.

It's not a blocking issue for me but I thought I'd write about it here before I forget.

Edit: In real life, don't pass a mutable as default. It would be shared by all field instances. Use a tuple.

**Comment by touilleMan** [comment]
I think your usecase is totally legit so we should add some checks in the `__init__` for the missing value:
- Make sure `missing` param provides an iterable or a callable
- if iterable, convert it to List : `missing = List(self.container, missing)`
- if callable, wrap it : `missing = lambda *args, **kwargs: List(missing(*args, **kwargs))`

On top of that we should add a word about this in ListField's documentation

**Comment by lafrech** [comment]
`DictField` is also affected.

I pushed a fix for this in https://github.com/Scille/umongo/pull/171.

It is along the lines of your proposal above.

The checks are performed after the call to `super().__init__` to avoid leaking data_object structures (`Dict` and `List`) to the pure marshmallow `Schema`. And because `self.container` is not defined before that.

At this point, I was tempted to call `self.deserialize` rather than `Dict` or `List`, and even to factorize than in `Field` itself. I don't think it would hurt. In fact, it would allow the user to pass default values in both serialized form and deserialized form (assuming the field can swallow its deserialized form, which I think is the case as this is the intent of the `_deserialize` override in some fields, such as `DateTime`). Since this might have other consequences, I left it aside for a moment.

Maybe `ReferenceField` should be addressed as well. It is a bit different and I don't really see the use case, so I'm leaving it as is.
