### ISSUE TITLE
Should EmbeddedDocument child of abstract EmbeddedDocument have a cls field?

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#86]
`EmbeddedDocument` and `Document` behaves differently with regards to the `cls` field:

- If `ChildDocument` inherits from `AbstractDocument`, it has no `cls` field.
- If `ChildEmbeddedDocument` inherits from `AbstractEmbeddedDocument`, it gets a `cls` field.

This results from a difference in the code:

```python
def _is_child(bases):
    """Find if the given inheritance leeds to a child document (i.e.
    a document that shares the same collection with a parent)
    """
    return any(b for b in bases if issubclass(b, DocumentImplementation) and not b.opts.abstract)

def _is_child_embedded_document(bases):
    """Same thing than _is_child, but for EmbeddedDocument...
    """
    return any(b for b in bases
               if issubclass(b, EmbeddedDocumentImplementation) and
               b is not EmbeddedDocumentImplementation)
```

I'm not sure I understand the rationale behind this.

We want to create an abstract parent `EmbeddedDocument` in our app with shared fields and methods for our `EmbeddedDocument`s to inherit, and now we get `cls` fields in every `EmbeddedDocument`, which pollute the API output. It would be easier to deal with this if it only happened when a concrete `EmbeddedDocument` is subclassed (which is much less frequent).

It's easy not to add `cls` from a concrete `EmbeddedDocument`s when its parent is abstract. Just copy `Document`:

```python
def _is_child_embedded_document(bases):
    """Same thing than _is_child, but for EmbeddedDocument...
    """
    return any(b for b in bases
               if issubclass(b, EmbeddedDocumentImplementation) and not b.opts.abstract)
```

but if we do that, we should also prevent `EmbeddedField` from accepting an abstract `EmbeddedDocument`, otherwise, it won't be able to deserialize that concrete child.

Is this the reason you did things this way?

It boils down to what we expect from an abstract `EmbeddedDocument`.

- For real polymorphism, where the abstract `EmbeddedDocument` is `Vehicle` and its children are `Car` and `Truck`, it makes sense to keep things the way they are. We may want to create an `EmbeddedField` that expects a concrete `Vehicle` subclass but not a `Vehicle`.

- If we create a `SuperEmbeddedDocument` for our `EmbeddedDocument`s to inherit, it does not make much sense to accept it in `EmbeddedField` and I don't see the use for the `cls` field.

It looks like we're dealing with two different concepts. Are we abusing inheritance by doing this? Should we do it differently? Should there be two different levels of abstraction?

Notes:

- If we keep things this way, we may need to add a protection in `EmbeddedField._deserialize` because IIUC, if value has no `cls` key, it will try to instantiate the parent abstract `EmbeddedDocument`, which will trigger `umongo.exceptions.AbstractDocumentError: Cannot instantiate an abstract EmbeddedDocument` rather than a `ValidationError` (I could be wrong, I didn't test that).

- Such a restriction applies to `Document`: you can't reference an abstract `VehicleDocument` since it has no collection.

- I don't see any simple way to prevent the API from spitting those `cls` fields out. Any nested structures with a little bit of complexity would require awful `params` trickery in `as_marshmallow_schema`.

**Comment by lafrech** [comment]
An approach to adding common methods to `EmbeddedDocument` could be to add a `BASE_EMBEDDEDDOCUMENT_CLS` to `BaseBuilder` with `EmbeddedDocumentImplementation` as default and overload `PyMongoBuilder` to provide our superclass. This could be an interesting feature request.

Our use case is a bit wider than this, though. We can have for instance:

```python
        class TimedEmbeddedDocument(EmbeddedDocument):
            created_at = DateTimeField()
            updated_at = DateTimeField()
```

Some `EmbeddedDocument`s would inherit from `EmbeddedDocument`, others from `TimedEmbeddedDocument`, or some other `EmbeddedDocument` subclass.

As opposed to `Vehicle`, there is no semantical link between `TimedEmbeddedDocument` and `Car` or `Truck`. I don't see a point for

```python
    field = EmbeddedField(TimedEmbeddedDocument)
```

Maybe we're trying to factorize too much.

Anyway, the more I think of it, the more I think current behaviour is correct.

We just need to find a reasonable way to remove those `cls` from the serialization.

I definitely need to think this through. I'll get back to you when my mind is clearer about it all.

Sorry about this mess...

**Comment by touilleMan** [comment]
Don't worry for the mess ;-)

I think the difference between embedded document and document is due to the fact a document is linked with a collection:
- Abstract document ==> no collection, cannot be instantiated
- Regular document ==> collection
- Regular Child document ==> same collection than it parent, get a `cls` field as discriminent

On the other hand, and embedded document has nothing to do with collections. However given it implementation comes from the document's one (doctstring of `EmbeddedDocumentOpts.abstract` shows this for example ^^), it get the abstract system.

I tried to fix what you described (see f178f2f92b02ba771de1ce7b017743532acb7a92):
- Abstract embedded document and it direct children don't provide `cls` field
- Abstract embedded document cannot be used in EmbeddedField

However I'm not sure this is the right way to do: is abstract really meaningful for embedded document ?
Without abstract, you would just define regular class (not `EmbeddedDocument`) to make my abstract inheritances, then use multiple inheritance to create concrete class.

This is typically what I would do to solve your current usecase btw:

```python
 class TimedEmbeddedDocumentMixin:
    created_at = DateTimeField()
    updated_at = DateTimeField()

class MyEmbeddedDoc(TimedEmbeddedDocumentMixin, EmbeddedDocument):
    foo = IntField()
```

So maybe we could just put a word about this pattern in the `EmbeddedDocument` documentation and drop the abstract stuff from it.

What do you think ? Do you see a special usecase that would require `abstract` for the embedded document ?

**Comment by lafrech** [comment]
Hi. Sorry for not answering any sooner.

I'm not used to mixins, and I don't know the pitfalls, but I blurringly remember there are pitfalls and I should have a clearer understanding of the MRO before using them, so I generally stick to "classical/linear" inheritance and scarcely use mixins. Therefore I can't provide educated feedback about this.

I like the abstract EmbededDocument idea. But I could probably live (just a guess, I didn't test) with the mixin approach if you prefer to follow that path.

**Comment by lafrech** [comment]
Mixins don't work (https://github.com/Scille/umongo/issues/188).

**Comment by lafrech** [comment]
I think both approaches (Mixin and base class) have their use case.

Typically, I'd use a Mixin to provide additional fields on some documents:

```py
 class TimedEmbeddedDocumentMixin:
    created_at = DateTimeField()
    updated_at = DateTimeField()

class MyEmbeddedDoc(TimedEmbeddedDocumentMixin, EmbeddedDocument):
    foo = IntField()
```

and I use a base class to provide additional methods to my base document, like wrappers to base methods, etc.

I pushed a PR fixing the Mixin issue (#267).

And I rebased @touilleMans' work on this in #269.

**Comment by lafrech** [comment]
Regarding the removal of `cls` field when dumping mentioned in OP, it is more or less unrelated.

I use a custom schema for this right now.

```py
class ExtraSchema(SchemaFromUmongo):
    """Custom Marshmallow Schema for our Schemas"""

    # XXX: This kinda sucks. Deal with it in umongo?
    def _init_fields(self):
        super()._init_fields()
        self.fields.pop('cls', None)
        self.load_fields.pop('cls', None)
        self.dump_fields.pop('cls', None)
```

This might be worth a umongo feature...
