### ISSUE TITLE
Motor 1.0+ support

### ISSUE THREAD

**Issue by ipfans** [Scille/umongo#87]
Motor 1.0 released 3 Nov 2016, it also have some support for MongoDB 3.4.

But, for now, umongo only support motor < 1.0 version.

**Comment by touilleMan** [comment]
I've worked on a branch to support motor>=1.0 (see https://github.com/Scille/umongo/tree/motor1) however it creates weird bugs with cursor count (see https://travis-ci.org/Scille/umongo/jobs/194090091#L407 and https://travis-ci.org/Scille/umongo/jobs/194090091#L563 for instance)

So I stopped the work there for the moment. Maybe it could be a good idea to open an issue on the motor bugtracker to get some help (those trouble look like regression given how simple is a7a327dd4b04ad6fdce435e949e7077243543fbf, the fix to be compatible with motor>=1)

**Comment by touilleMan** [comment]
@ipfans port to motor 1.1 is done \o/ (see 882bdede20dd508b292b88a4b7563b87ad11ab6c)

**Comment by ipfans** [comment]
Thx for your works!
