### ISSUE TITLE
Mess of pymongo versions

### ISSUE THREAD

**Issue by imbolc** [Scille/umongo#9]
Hi :)

It looks like pymongo driver implemented for pymongo3, but motor driver for pymongo2.
So if I install lib for motor, I can't use it with pymongo. E.g. if i try to run homepage sample, I got:
```
Traceback (most recent call last):
  File "test_umongo_1.py", line 18, in <module>
    goku.commit()
  File "/home/imbolc/.pyenv/versions/3.5.0/lib/python3.5/site-packages/umongo/dal/pymongo.py", line 70, in commit
    ret = self.collection.insert_one(payload)
  File "/home/imbolc/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pymongo/collection.py", line 1773, in __call__
    self.__name.split(".")[-1])
TypeError: 'Collection' object is not callable. If you meant to call the 'insert_one' method on a 'Collection' object it is failing because no such method exists.
```

**Comment by touilleMan** [comment]
Yeah, the main trouble is motor needs pymongo==2.8 exactly.
On the other hand txmongo wants pymongo>=3.0, so does umongo-pymongo dal.

This means you cannot share the same environment to work with both motor and pymongo/txmongo.

I've seen it is plan for motor to [switch to pymongo>3.0](https://jira.mongodb.org/browse/MOTOR-87). When it'll be done we will upgrade motor dal and drop pymongo 2.8 api.

**Comment by imbolc** [comment]
Thanks a lot for clarifying. I hope they will do this. Because it's usual case when motor used with aiohttp for web server. And pymongo for this site cli scripts. And now we should use different venvs for server and scripts, or use raw pymongo for scripts.

**Comment by touilleMan** [comment]
I agree, beeing able to use motor/txmongo and pymongo in the same project with the same datamodel was one of my goal when starting umongo.

I think a solution could be to create a `pymongo28` dal which would be essentially a rehash of the regular `pymongo` dal with only a couple of fix where the api changes.
