### ISSUE TITLE
marshmallow {pre,post}_{load,dump} functions handled as fields

### ISSUE THREAD

**Issue by ribx** [Scille/umongo#90]
When I added a @pre_load decorator to a function in my Document class:

```
@instance.register
class Test(Document):
    name = fields.StringField()

    @pre_load
    def test(self, data):
        return data
```

the function is handled like a field and I end up with the error:

    (...)
      File "/<path_to_venv>/lib64/python3.4/site-packages/umongo/schema.py", line 15, in find_id_field
        if (name == '_id' and not field.attribute) or field.attribute == '_id':
    AttributeError: 'function' object has no attribute 'attribute'

I check the tests (*test_document.py*), and it looks like there the error is avoided by defining

```
name = fields.StrField(attribute='_id')  # Overwrite automatic pk
```

which for me is not the sense of these tests.

Also, the tests are run with their own *MokedBuilder*, which avoids tests with the real builders. There I found another error (again because the function is treated like a field):

      File "/<path_to_venv>/lib64/python3.4/site-packages/umongo/frameworks/pymongo.py", line 296, in _patch_field
        validators = field.io_validate
    AttributeError: 'function' object has no attribute 'io_validate'

I corrected the errors where they appear, for now, but I think a real fix would look different.

The function `builder._collect_fields()` is responsible for separating "fields and non-fields" as the docstring says, but I am not sure why items with a `__marshmallow_tags__` attribute are include to the fields here.

Please help me to find the right place to fix this issue.

**Comment by touilleMan** [comment]
Hi, thx for the issue !

Commit 3ac6bfcc30dec5d2d5326b3d725bb2e7b6917d73 should have fixed this bug 👍 

Please, reopen if the bug is still there

**Comment by ribx** [comment]
There are some things remaining, I will open new bugs.
