### ISSUE TITLE
Synchronizing referencer and referenced document

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#91]
I've been hit by this. Sometimes you have a Document and a referenced Document and when you're working on both instances at the same time you can find yourself in a sort of broken state.

I've pushed [a branch](https://github.com/Nobatek/umongo/commits/dev_jl_ref_fetch) with commented tests to explain the idea.

Currently, fetch() fetches from the database, so if you have a referenced Document instance you're working on, the changes won't be seen until it is committed and the Document is reloaded. This is shown [here](https://github.com/Nobatek/umongo/commit/852b58676fdc8e6f165de2d6e159668568fc631a).

The branch shows two measures that would mitigate this:

- Ensure that when assigning a Document to the reference field, that Document is set as _document so that fetch returns it even if it is not committed in DB. Shown [here](https://github.com/Nobatek/umongo/commit/b62fc9b756dd0deb6456d386f71a780f1811605b). Admittedly It looks like a bit of a hack. The point is to see what behavior this would provide.

- Provide a `force_reload` parameter to fetch() so that if the referenced Document instance is committed, it is possible to refresh the reference without reloading the whole Document. Shown [here](https://github.com/Nobatek/umongo/commit/7e0e46a9c92362b4a03fb178935e5deada1dea14).

I'm not sure about the first approach. It looks like it strives for providing a transparent reference management, but this is bound to fail at some point, so we'd rather keep things explicit.

On the other hand, the `force_reload` parameter is explicit and has limited impact. It just avoids reloading the whole Document (which could be problematic if work is ongoing). Without this (and without the other approach described above), there is no way to get fetch() to return the updated Document if it has changed in DB.

In fact, the more I think of it, the more the `force_reload` approach seems like the right approach to me. Anyway, I'm exposing both here for feedback.

**Comment by lafrech** [comment]
Functionally, `force_reload` is equivalent to fetch() + reload() (shown [here](https://github.com/Nobatek/umongo/commit/d83649ca44cdaf6ab387260f02b7a2eff7072b01)).

Nothing really new, then. Yet, it might be handy as it allows one-liners since fetch returns the instance while reload does not.

**Comment by touilleMan** [comment]
I like you suggestion of providing this `force_reload` option, this helps underlying the fact that de referenced document is cached and should be modified with care then.

Waiting for your PR now ;-)

**Comment by lafrech** [comment]
Thanks for the feedback. We're awfully late on our app dev right now, so I can't promise I'll be able to do it any soon...
