### ISSUE TITLE
Many tests are not done with a real framework

### ISSUE THREAD

**Issue by ribx** [Scille/umongo#92]
As I mentioned in https://github.com/Scille/umongo/issues/90, many tests are only done against the pseudo database. A better solution would be to have all tests test against every database driver.

**Comment by touilleMan** [comment]
Most of the tests in the `tests` folder are done against a single feature so using a pseudo database is not a big deal given.

Beside it would be very cumbersome to test with each framework given they are both synchronous and asynchronous (hence we need to add the `yield from ` stuff)

However you advice was valuable for the `test_instance`, which is now parametrize to test against each framework (before that each framework had some test about this in `tests/frameworks`, I removed them given they are redundant now).
