### ISSUE TITLE
default values are not stored in database

### ISSUE THREAD

**Issue by ribx** [Scille/umongo#93]
As default values are not stored in the database, things like
```
    _version = fields.IntField(default=1)
    date_created = fields.DateTimeField(default=datetime.utcnow())
```
make no sense (as the _version is meant to document the _version of the object in the database to allow lazy migrations later on).

Is there another approach to achieve this?

**Comment by ribx** [comment]
Just found the "missing" parameter in tests. Nevermind.

**Comment by lafrech** [comment]
@ribx you may be interested in https://github.com/Scille/umongo/issues/36.

default/missing are bound to be reworked.
