### ISSUE TITLE
lazy migrations

### ISSUE THREAD

**Issue by ribx** [Scille/umongo#94]
Lazy migration is a really handy feature when it comes to big production databases.

Where would be the best place to implement them? Inside the DataProxy?

**Comment by touilleMan** [comment]
Hi ribx,

UMongo is pretty transparent regarding the fields it maps in the database.
- IF `_id` field is not defined in the Document, it is considered as a regular ObjectId
- a string `_cls` field is added to Document defined as children (e.g. within a same collection you have `Animal` and `Dog` objects, then `Dog` will have a `_cls` field set as `Dog`)

This is basically what Mongoengine does so if you migrate from it you should have nothing to do ;-)

On the other hand, if you data are more clunky (e.g. some fields are not consistent), you can take advantages of the fact umongo uses marshmallow behind the scene to do [pre-load checks](http://marshmallow.readthedocs.io/en/latest/extending.html#pre-processing-and-post-processing-methods):

```python
class Animal(Document):
    name = fields.StringField()
    age = fields.IntField()
    # define your field as you want them to be in the end

    @pre_load
    def lazzy_migration(self, in_data):
        # This allows you to transform the data before loading them into umongo's schema
        in_data['name'] = in_data.pop('deprecated_field_name', 'Unknown')
        # ...
        return in_data
```

**Comment by ribx** [comment]
@touilleMan: Yes, I saw these possibilities. But this is intented to run on data that is coming from the userinterface, not from the database!

Check this code here: 

https://github.com/Scille/umongo/blob/master/umongo/document.py#L199

`doc = cls()` will trigger @pre_load - I don't know why and this is possibly an error - but without any data.

One way to implement lazy migrations would be to have also "@<pre|post>_<from|to>_mongo decorators.

**Comment by touilleMan** [comment]
You're right about this, marshmallow pre/post stuff is intended for data coming from user.

> doc = cls() will trigger @pre_load - I don't know why and this is possibly an error - but without any data.

UMongo policy is to check data consistency when modified (for example `Doc(int_field="not an int")` or `doc.int_field = "not an int"` would trigger a exception) except for the `required` attribute which is checked when calling `doc.commit()` (the idea is you could want to build your document in multiple steps)

Thus, `doc = cls()` is here to create a new default instance of the document, then we load the data from the database inside it (not that umongo trust data coming from the database so it doesn't check it consistency).

So in the end ou should consider overloading the `MyDocument.from_mongo` method which will be called with the raw data from the database and insert them in the data proxy. Considering my previous example:

```python
class Animal(Document):
    name = fields.StringField()
    age = fields.IntField()
    # define your field as you want them to be in the end

    def from_mongo(self, data, partial=False):
        # This allows you to transform the data before loading them into umongo's data proxy
        data['name'] = data.pop('deprecated_field_name', 'Unknown')
        # ...
        return super().from_mongo(data, partial=partial)
```
